### ISSUE TITLE
Tag Creation not working correctly for repos with main as default branch

### ISSUE THREAD

**Issue by kahootali** [anothrNick/github-tag-action#100]
Since Github has changed the default branch to `main`, so now this action is not working as expected, it creates tag with vMAJOR.MINOR.PATCH-beta.1 whereas I don't want beta-1, I have added main in my RELEASE_BRANCHES as well, but still it doesn't work..

This is my Github action workflow for main branch
https://github.com/kahootali/dotnet-core-github-actions/blob/main/.github/workflows/main.yml

And this is the repo link, that I am trying to add this action to.

https://github.com/kahootali/dotnet-core-github-actions

**Comment by kahootali** [comment]
The same is working fine with master branch repos, and even though 
I have tested on version 1.26 as well and latest as well, seems like it affects all versions

**Comment by anothrNick** [comment]
@kahootali  Fix included in https://github.com/anothrNick/github-tag-action/releases/tag/1.34.0
