### ISSUE TITLE
POST Suffix for custom incremented label names

### ISSUE THREAD

**Issue by iceicys** [anothrNick/github-tag-action#103]
So I see that there is a `PRERELEASE_SUFFIX` option available however for my teams tagging convention for Release Branches we use the following format for release candidate labels. I'm wondering if there's a way to accomplish the following:
**Branch (1.0.0)**
- 1.0.0-rc.1
- 1.0.0-rc.2
- 1.0.0-rc.3
- 1.0.0-rc.4
- 1.0.1 (release version)

**Comment by anothrNick** [comment]
The utility I'm using does have a way of doing this, e.g.
```
$ semver 1.2.4-beta.0 -i prerelease
1.2.4-beta.1
```

Where I believe you could do 
```
$ semver 1.0.0-rc.1 -i prerelease
1.0.0-rc.2
```

As long is it still uses the latest tag relevant to the release candidate suffix...

**Comment by sammcj** [comment]
Hello @iceicys - is this still an issue with v1.45.0 and required?

**Comment by sbe-arg** [comment]
Closing please reaopen if necesary
