### ISSUE TITLE
Output Components

### ISSUE THREAD

**Issue by deefdragon** [anothrNick/github-tag-action#104]
Right now I need to use a second step to calculate the major minor and patch numbers. Would it be possible to add as outputs the Major Minor and Patch values?

**Comment by anothrNick** [comment]
The library I'm using doesn't seem to expose a way (via command line) to pull that out, although it does provide ways of doing it when using as a node library (I regret initially writing this in bash 😬 ). Also, splitting on `.` could get messy with potential prefix/suffix stuff that's been added.

How are you currently pulling the values out of the version?

**Comment by deefdragon** [comment]
I use [booxmedialtd/ws-action-parse-semver](https://github.com/marketplace/actions/parse-semver)

**Comment by sammcj** [comment]
Hello - is this still an issue with v1.45.0 and required?

**Comment by sbe-arg** [comment]
Closing please reaopen if necesary
