### ISSUE TITLE
Don't increment the version tag if the current commit has been tagged

### ISSUE THREAD

**Issue by reececomo** [anothrNick/github-tag-action#11]
Love this project, just started using it in a private repo.

Occasionally we trigger this GitHub Action remotely for a blank deploy/re-deploy. It would be great if there was an early-exit check like (pseudocode):

```
if HEAD == COMMIT {
    echo "Commit already tagged as version $VERSION"
    return 0;
}

**Comment by anothrNick** [comment]
Resolved with https://github.com/anothrNick/github-tag-action/releases/tag/1.5.0

@reececomo Thanks for the contribution!!
