### ISSUE TITLE
Using the action doesn't invoke a push event

### ISSUE THREAD

**Issue by sohmc** [anothrNick/github-tag-action#110]
I'm not sure if I'm just not doing this right.  My workflow is:

1. Make changes in a branch
2. Actions does testing in the branch with each commit
3. When all tests pass and features are done, merge create PR to merge with main
4. When pushing to main, create tag
5. When tag is pushed, trigger a draft release with another action.

The problem I'm running into is Step 5.  When using this action, the tag is pushed, it doesn't actually trigger a push event.  [You can review the logs here](https://github.com/sohmc/github-actions-testing/actions)

When I manually create the trigger and push it to github, the push is registered and the create-release-draft job fires.

My expectation is that github would see the push and then fire off another invocation of the workflow from the tag.  Any idea why it wouldn't?

**Comment by vearutop** [comment]
I think is happens because Github Actions default token is not allowed to trigger actions, relevant discussion: https://github.community/t/github-actions-workflow-not-triggering-with-tag-push/17053/4.

**Comment by anothrNick** [comment]
@sohmc as @vearutop mentioned I believe you'll need to pass a personal access token as the `GITHUB_TOKEN` environment variable rather than the default token.

**Comment by sohmc** [comment]
@anothrNick that fixed it.  Thanks!
