### ISSUE TITLE
Tag is not pushed when using a selfhosted runner

### ISSUE THREAD

**Issue by BeMacized** [anothrNick/github-tag-action#115]
Up until now, I have been using this action with great success, using GitHub's own runners. 
When experimenting with using my home server as a self-hosted runner, I ran into an issue with this action.

The action itself succeeds, but it fails to push a tag and shows a few errors in the logs:

```
*** CONFIGURATION ***
	DEFAULT_BUMP: PATCH
	WITH_V: false
	RELEASE_BRANCHES: master
	CUSTOM_TAG: 
	SOURCE: .
	DRY_RUN: false
	INITIAL_VERSION: 0.0.0
	TAG_CONTEXT: repo
	PRERELEASE_SUFFIX: testing
	VERBOSE: true
fatal: not a git repository (or any parent up to mount point /github)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Is master a match for 
pre_release = true
fatal: not a git repository (or any parent up to mount point /github)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /github)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /github)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /github)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /github)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /github)
No new commits since previous tag. Skipping...
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

I am personally fine just using GitHub's own runners, but in case you are interested in looking into it:

I run the runner on my home server in docker. It uses the docker image `tcardonne/github-runner:latest`. 
If any necessary information is missing, I'd be happy to provide.

**Comment by jessewmc** [comment]
There seems to be some strange interaction between the action docker container git and the os if the self hosted runner does not have git installed (or has a very old version installed).

I'm not clear why this is happening, but installing a recent version of git on my self hosted runner fixed the problem.

**Comment by trevor92** [comment]
At my company we started tried using self-hosted runners, I am also running into the same issue as BeMacized, I will reach out to our Site Reliability Engineering team to see if they can update the runner's git version per jessewmc's suggestion as see if that resolves the issue.

**Comment by sammcj** [comment]
Hello - is this still an issue with v1.45.0 and required?

**Comment by sbe-arg** [comment]
Has been resolved, please reopen if necesary is used in self hosted runners here for example 1.39.0 https://github.com/bridgecrewio/checkov-action/blob/master/.github/workflows/build.yml

**Comment by fantasywind** [comment]
It possibly caused by docker in docker volume feature, if you run a github runner as docker container and mount workspace from your host server. When github-tag-action run, it will run a new container in your runner container. 

By docker run defaults, the volume source path is reference from host os system not container file system. To solve this issue, run your github runner container with same workspace path equal to host os.

e.g. 
```shell
docker run -d --name Runner -v /var/github-runner:/var/github-runner {RunnerImage}
```

and remember set the workspace path as /var/github-runner

**Comment by sbe-arg** [comment]
Gold tip, thanks!
