### ISSUE TITLE
Output tag without 'v' prefix

### ISSUE THREAD

**Issue by skst** [anothrNick/github-tag-action#116]
Thank you for providing this action.

I would like to use the new tag without the `v` for the name of my release. Unfortunately, GitHub does not provide string manipulation. I can run this action with **DRY_RUN** to get the tag without the `v`, but it would be more convenient if it were one of the outputs.

Thank you for considering this enhancement.

**Comment by anothrNick** [comment]
@skst  `WITH_V` is an optional environment variable that is set to `true` in the example config in the README. If you remove this or set it to `false` the tag will be generated without the prefix.

I primarily use this action without any prefix.

**Comment by skst** [comment]
Absolutely, and I like that it's optional. After I use `github-tag-action` to tag the branch, I use [`create-release`](https://github.com/marketplace/actions/create-release) to create a release and attach an artifact. I want to name the release with the version but without the `v` prefix. Currently, I have to run `github-tag-action` with **DRY_RUN** set to _true_ to get the tag without the `v` prefix. It would be more convenient if **both** the tag with prefix and without were outputs of the actual run.

**Comment by anothrNick** [comment]
Ah I see, so you want the tag to exist in Github _with_ the prefix, but want to include it in the name of the release _without_ the prefix.

Although the `tag` output on Dryrun is the old tag 

```
https://github.com/anothrNick/github-tag-action/blob/master/entrypoint.sh#L144
```

Regardless, we could set another output here: https://github.com/anothrNick/github-tag-action/blob/master/entrypoint.sh#L115
Which would be without the `v` prefix.

**Comment by skst** [comment]
> Ah I see, so you want the tag to exist in Github with the prefix, but want to include it in the name of the release without the prefix.

Exactly.

> Although the tag output on Dryrun is the old tag

Hmm. It seems to be outputting the new tag for me. It's working great.

![image](https://user-images.githubusercontent.com/74487/118686761-ed270900-b7c9-11eb-8a28-a46c79945cdf.png)

> Regardless, we could set another output here ... Which would be without the v prefix.

That would be awesome. 👍

**Comment by sbe-arg** [comment]
https://github.com/anothrNick/github-tag-action/pull/157

**Comment by sbe-arg** [comment]
This has been resolved closing
