### ISSUE TITLE
Update docs page on marketplace

### ISSUE THREAD

**Issue by miguelaferreira** [anothrNick/github-tag-action#121]
I spent quite some time trying to get pre-releases working while always getting this message "This branch is not a release branch. Skipping the tag creation.". I looked through several issues and some did indicate that pre-releases should work, one even referenced a PR to introduce the suffix for them. It was only when I looked in the code that I realised I was prolly running an old version of the action because the error message I was seeing wasn't even in the code anymore. 

Could you please update the docs page on the marketplace to a version for which pre-release actually works?
This one: https://github.com/marketplace/actions/github-tag-bump

Also, thanks for the action, it's really handy!

Edit: also maybe remove the sentence " Other branches and pull-requests generate versions postfixed with the commit hash and do not generate any tag." because it seems the action doesn't work this way anymore.

**Comment by yurirocha15** [comment]
Adding to this issue, the latest release was done 8 months ago. Since then there were some important changes like #107 (which is in the README, but can't be used) #109 #112. Would be nice to have a new release before focusing on v2.

**Comment by anothrNick** [comment]
Just pushed `1.36.0` to the marketplace with the latest version in the readme
