### ISSUE TITLE
unexpected behavior of bumping when using prerelease

### ISSUE THREAD

**Issue by jonathan-kaufman-by** [anothrNick/github-tag-action#127]
I am attempting to use both release and pre-release branches, with the repo tag context.
We have a main branch which is our "release" branch, a develop branch which is our pre-release branches and feature/* branches which feed into develop.

To set the stage on the tags, and observations up to the point where I got something unexpected.

```
# 0.0.1-beeta.1 (PR to develop, bump:patch ) --> Use the default version in action (0.0.0)
# 0.0.1-beeta.2 (Direct Push to develop, bump:patch)
# 0.1.0 (PR to main from develop, bump:minor)
# 0.1.1-beeta.1 (PR to develop, bump:patch)
# 0.2.0-beeta.1 (PR to develop, bump:minor)
# 0.2.0 (PR to main, bump:minor)
# 1.0.0-beeta.1 (PR to develop, bump:major)
# 0.3.0-beeta.1 (PR to develop, bump:minor) <--- Unexpected, *should* I not get 1.0.0.beeta.2 or 1.1.0.beeta.1?
```

The action ends up generating 0.3.0-beeta.1 in the above scenario due to the resulting false value in the IF statement here: https://github.com/anothrNick/github-tag-action/blob/master/entrypoint.sh#L109

Is this an expected SEMVER behavior and "I'm doing it wrong", or is this more of a logic edge case bug?

```
*** CONFIGURATION ***
	DEFAULT_BUMP: minor
	WITH_V: false
	RELEASE_BRANCHES: main,master
	CUSTOM_TAG: 
	SOURCE: .
	DRY_RUN: false
	INITIAL_VERSION: 0.0.0
	TAG_CONTEXT: repo
	PRERELEASE_SUFFIX: beeta
	VERBOSE: true
Is main a match for develop
Is master a match for develop
pre_release = true
Merge pull request #119 from xxxx/tag14 tag14 tag14 Merge pull request #118 from xxx/tag12 tag12 tag12 Merge pull request #117 from xxxx/tag11 tag11 tag11 tag10 (#116) tag10 Merge pull request #115 from xxx/tag9 Test Squash Commit Disable workflows Merge pull request #114 from xxx/tag8 tag8 tag8
pre-minor
Bumping tag 1.0.0-beeta.1. 
	New tag 0.3.0-beeta.1
```

**Comment by abhinav812** [comment]
+1Happening the same with me

**Comment by sammcj** [comment]
Hello - is this still an issue with v1.45.0 and required?

**Comment by sbe-arg** [comment]
Has been resolved, please reopen if necesary
