### ISSUE TITLE
Allow to define custom description for tag

### ISSUE THREAD

**Issue by samuelbernardolip** [anothrNick/github-tag-action#129]
Current implementation uses the description of last commit and associate that with the tag.
Would be useful, if possible, to apply a custom description for the tag, overriding the commit message.

**Comment by sammcj** [comment]
Hello - is this still an issue with v1.45.0 and required?

**Comment by samuelbernardolip** [comment]
Hello @sammcj 
Need to check that, but about the requirement I would say yes, since custom description for the tag is not an option as I check previously. What I mean about custom description for the tag is the same as when defining message for annotated tags.
Thanks

**Comment by sammcj** [comment]
Thanks for your response @samuelbernardolip , so the ability to use annotated tags would resolve this for you? If so I'll close this as a dupe of #81

**Comment by samuelbernardolip** [comment]
Hi @sammcj 
Yes, this is a dup of #81 in that case. Closing this issue.
Thanks
