### ISSUE TITLE
Existing "v"-prefixed tag yields incorrect non-"v"-prefixed bump

### ISSUE THREAD

**Issue by kevingentile** [anothrNick/github-tag-action#130]
We previously tagging releases as `vx.x.x` and switched to `x.x.x`. We then manually tagged a release `1.2.0`. The command that provided pre-tags yields the `v`-prefixed tags first instead of the most recent `1.2.0`:

```
$ git tag --list --merged HEAD --sort=-v:refname | grep -E "^v?[0-9]+\.[0-9]+\.[0-9]+$" | head -n1
v1.0.23
v1.0.22
...
1.2.0
```

Instead of a minor bump to `1.2.1` we get a patch bump to `1.0.24`.

**Comment by bevans-HD** [comment]
In my case, the tag bump is still failing. Investigating now.

**Comment by bevans-HD** [comment]
Small typo in `entrypoint.sh` https://github.com/anothrNick/github-tag-action/blob/3272e7a58f6c71ee9ede35f53b114e1bb9a91347/entrypoint.sh#L50

Missing `$` in front of `with_v`
```
if [ with_v ]
then 
    tagFmt="^v?[0-9]+\.[0-9]+\.[0-9]+$"
    preTagFmt="^v?[0-9]+\.[0-9]+\.[0-9]+(-$suffix\.[0-9]+)?$"
fi```

**Comment by bevans-HD** [comment]
This effectively forces "WITH_V" true for everyone. Also, this patch doesn't account for someone turning WITH_V back on again. @anothrNick you might want to revert, or that the very least change `if [ with_v ]` to `if $with_v`

**Comment by bevans-HD** [comment]
My above comment wasn't quite correct. The current master will simply use the same regex that it was using before this patch. i.e. always limiting the latest tag to the most recent `v` prefixed tag if WITH_V was ever used.

This small PR fixes it: https://github.com/anothrNick/github-tag-action/pull/133

**Comment by bevans-HD** [comment]
OK, this PR is a little more involved, but address the lingering issues leftover in #133 

https://github.com/anothrNick/github-tag-action/pull/134. I'm going to close #133 because I think #134 is a better solution
