### ISSUE TITLE
fatal: ambiguous argument '0.4.0..HEAD': unknown revision or path not in the working tree.

### ISSUE THREAD

**Issue by artem-tomyuk** [anothrNick/github-tag-action#135]
Hi, 

getting errors(log below) on a latest version of github-tag-action 1.38 while bumping the tag, so i decided to rollback version of github-tag-action to 1.36.0 and it solved the issue.
so i guess errors are related to latest changes in 1.38 or 1.37 tag.

*** CONFIGURATION ***
	DEFAULT_BUMP: minor
	WITH_V: true
	RELEASE_BRANCHES: master,main
	CUSTOM_TAG: 
	SOURCE: .
	DRY_RUN: false
	INITIAL_VERSION: 0.0.0
	TAG_CONTEXT: repo
	PRERELEASE_SUFFIX: beta
	VERBOSE: true
Is master a match for devel
Is main a match for devel
pre_release = true
From https://github.com/kastapost/auth.kastapost.ua
 * [new branch]      master          -> origin/master
 * [new branch]      rights-requests -> origin/rights-requests
 * [new branch]      smart-login     -> origin/smart-login
 * [new branch]      themed-auth     -> origin/themed-auth
 * [new branch]      wms-auth        -> origin/wms-auth
 * [new tag]         v1.0.0          -> v1.0.0
 * [new tag]         v1.1.0-beta.1   -> v1.1.0-beta.1
 * [new tag]         v1.1.0-beta.2   -> v1.1.0-beta.2
 * [new tag]         v1.1.0-beta.3   -> v1.1.0-beta.3
 * [new tag]         v2019.2         -> v2019.2
fatal: ambiguous argument '1.0.0..HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument '1.0.0': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

pre-minor
Bumping tag . 
	New tag v1.1.0-beta.1
fatal: tag 'v1.1.0-beta.1' already exists
  "message": "Reference already exists",
  "documentation_url": "https://docs.github.com/rest/reference/git#create-a-reference"
}
Error: Tag was not created properly.

**Comment by inih** [comment]
I'm also running into the same issue and getting the same error. Reverting to version 1.36.0 fixed it.

**Comment by craigrileyuk** [comment]
Same:

```
*** CONFIGURATION ***
	DEFAULT_BUMP: none
	WITH_V: true
	RELEASE_BRANCHES: main
	CUSTOM_TAG: 
	SOURCE: .
	DRY_RUN: false
	INITIAL_VERSION: 0.0.0
	TAG_CONTEXT: repo
	PRERELEASE_SUFFIX: beta
	VERBOSE: true
Is main a match for main
pre_release = false
fatal: ambiguous argument '0.0.13..HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument '0.0.13': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

Default bump was set to none. Skipping...
```

**Comment by alexeyatbluescape** [comment]
I no longer get this error with my fix: https://github.com/anothrNick/github-tag-action/pull/155.

feel free to test with `alexeyatbluescape/github-tag-action@bugfix/semver-empty-results`

**Comment by Norgul** [comment]
I am using `v1.39.0` and issue is still there.

**Comment by justin-newman** [comment]
looks like there is a PR that is supposed to fix this. it just needs a review and all that: [#157](https://github.com/anothrNick/github-tag-action/pull/157)

**Comment by ChrisHolcomb** [comment]
I tried using 1.39 and had same issue, just switched to 1.36 and works fine now.

**Comment by sammcj** [comment]
Hello - is this still an issue with v1.45.0?
