### ISSUE TITLE
Fatal ambiguous argument with 'multiple'

### ISSUE THREAD

**Issue by Benjamintdk** [anothrNick/github-tag-action#139]
Ran into this issue of creating a new tag on 1.38.0. I have included a picture of the code as well, and there was an actions checkout done before this with fetch depth of 30 included. I fixed this by switching back to 1.36.0.

![tag issue](https://user-images.githubusercontent.com/45474952/159393800-462862b5-2df4-4e75-b311-27f1ae1772bc.png)

![gh tag](https://user-images.githubusercontent.com/45474952/159394101-44789ba9-ee60-4e84-ba61-64db8c929b6b.png)

**Comment by nVizzz** [comment]
Faced with this situation on 1.39.0 too.
I also fixed this by switching back to 1.36.0.
@Benjamintdk thank you for your advice!

**Comment by rlanga** [comment]
I'm facing this issue too. But switching back to `1.36.0` means I won't have the `fatal: unsafe repository ('/github/workspace' is owned by someone else)` fix. So both versions are broken at the moment 🥲

**Comment by sbe-arg** [comment]
https://github.com/anothrNick/github-tag-action/pull/157

**Comment by sbe-arg** [comment]
Has been resolved, please reopen if necesary
