### ISSUE TITLE
Only latest tag with v prefix is found in mixed repo tags.

### ISSUE THREAD

**Issue by richkifvel** [anothrNick/github-tag-action#141]
Hi, 
I am looking to add this versioning action to our actions. The existing versioning setup doesn't include a `v` for a prefix. I used the `WITH_V: true` flag initially to distinguish between test pipeline & prod pipeline.

I see in[ your code](https://github.com/anothrNick/github-tag-action/blob/37ff4873ee1e9b43cb25a7817cb15b2128536b84/entrypoint.sh#L50) that when fetching the latest tag it should not matter if the `v` prefix is assigned but I find that, now that we have `v` prefixed tags in the repo, these are the only ones that are found as the latest despite having many more subsequently created without the prefix.

Another downside to this is that the actions fails to pick up the new tags trying to be created with `WITH_V: false` set . It keeps trying to create a tag that already exists.

**Comment by mazilu88** [comment]
I just bumped into the same issue. I want the new tags to don't have 'v' but it keeps bumping only the latest tag with 'v'

Bumping tag v1.2.0. 
	New tag 1.3.0
fatal: tag '1.3.0' already exists

**Comment by drusellers** [comment]
Just ran into this as well when switching from `WITH_V: true` to `WITH_V: false`.

I upgraded to `1.39.0` and it seems to have gone away.

**Comment by sbe-arg** [comment]
https://github.com/anothrNick/github-tag-action/pull/157

**Comment by sammcj** [comment]
This should now be resolved, please let me know if it isn't.
