### ISSUE TITLE
Stopped working with latest Git update

### ISSUE THREAD

**Issue by g12i** [anothrNick/github-tag-action#147]
After following update https://github.blog/2022-04-12-git-security-vulnerability-announced/

The action stoped working and I'm getting:

```
➡️  Run anothrNick/github-tag-action@1.26.0

fatal: unsafe repository ('/github/workspace' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
```

**Comment by sbe-arg** [comment]
https://github.com/anothrNick/github-tag-action/pull/145

**Comment by sbe-arg** [comment]
v1.36 uses alpine 3.10 wich is EOL. check PR145

**Comment by anothrNick** [comment]
Deployed that update with `1.39.0`
