### ISSUE TITLE
WITH_V issue: commits are not read to select how to bump version

### ISSUE THREAD

**Issue by gusmith** [anothrNick/github-tag-action#150]
With version 1.39.0

When getting the latest tag, `semver` is used (https://github.com/anothrNick/github-tag-action/blob/master/entrypoint.sh#L57 and https://github.com/anothrNick/github-tag-action/blob/master/entrypoint.sh#L64)
When using `WITH_V`, the git tags are prefixed with the `v` character which is ignored and stripped by `semver`.

The problem is then when a tag exists, and the code tries to get the list of newer commit: it uses directly the output of `semver` instead of prefixing it again with the character `v`: https://github.com/anothrNick/github-tag-action/blob/master/entrypoint.sh#L83

E.g., if the latest version is `v1.2.3`, the attribute `tag` will be equal to `1.2.3` which is **not** a git tag, thus the command `git log 1.2.3..HEAD` fails with a 
```
fatal: ambiguous argument '1.2.3..HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument '1.2.3': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

This becomes a complex logic due to the PR #134 which mixes all possible versions (with a prefix `v` and without). Thus after `semver` (if we list ALL the tags available), the code cannot know if it was or not prefixed with a `v`...

**Comment by gusmith** [comment]
I am not fully sure, but I believe they are related to the issues #135 and #140

**Comment by ltshb** [comment]
I've the same issue, when I push a commit with `#patch` in the message, github-tag-action cannot retrieve the last tag
```bash
 * [new tag]         v3.3.0         -> v3.3.0
 * [new tag]         v3.3.0-beta.1  -> v3.3.0-beta.1
 * [new tag]         v3.4.0-beta.1  -> v3.4.0-beta.1
fatal: ambiguous argument '3.3.0..HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument '3.3.0': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

minor
Bumping tag 3.3.0. 
	New tag v3.4.0
::set-output name=new_tag::v3.4.0
##[debug]steps.tagging.outputs.new_tag='v3.4.0'
::set-output name=part::minor
##[debug]steps.tagging.outputs.part='minor'
::set-output name=tag::v3.4.0
##[debug]steps.tagging.outputs.tag='v3.4.0'
```

**Comment by petelah** [comment]
@ltshb We have the same issue, reverted back to 1.36 and all is fine again.

**Comment by ltshb** [comment]
@petelah unfortunately version 1.36 don't work anymore due to the github unsafe directory security issue. I forked the repo and created a fix for this issue, see #151

**Comment by rlanga** [comment]
@ltshb I see that the PR was closed. How come?

**Comment by ltshb** [comment]
@rlanga sorry I unintentionally deleted my branch on my fork as it was there merged which closed the PR here. I readed the branch and reopened the PR.

**Comment by rlanga** [comment]
Seems like review times are pretty long. Is there any maintainer we can kindly poke to look at the PR?

**Comment by ltshb** [comment]
@anothrNick I think many people would be grateful if you can have a look at #151 :-)

**Comment by alexeyatbluescape** [comment]
alternative fix (that does not require specification of last version): https://github.com/anothrNick/github-tag-action/pull/155
try: alexeyatbluescape/github-tag-action@bugfix/semver-empty-results

**Comment by ltshb** [comment]
@alexeyatbluescape unfortunately your fix #155  does not solve the issue if the repo contains tag with and without `v` prefix.

**Comment by crunk1** [comment]
Somebody mentioned their in-comment `#patch` being ignored. I just had the same issue with `#minor`

**Comment by sbe-arg** [comment]
too see all commits u must have checked out with 0 depth otherwise you have no commits (I know you know this but as reminder for audience)

see https://github.com/anothrNick/github-tag-action/pull/157 I think is as simple as changing the regex and the filter with or without v to select tags properly when match

**Comment by zozoxo1** [comment]
https://github.com/fhswf/JupyterHub-Autotagger-Action/tree/v1.0.3 this should fix the issue if you set with_v to true

**Comment by sammcj** [comment]
Hello - is this still an issue with v1.45.0?

**Comment by sbe-arg** [comment]
Has been resolved, please reopen if necesary
