### ISSUE TITLE
`CUSTOM_TAG` ignored when `DEFAULT_BUMP` is `none`

### ISSUE THREAD

**Issue by morey-tech** [anothrNick/github-tag-action#159]
When using the `CUSTOM_TAG`, if the `DEFAULT_DUMP` is set to `none` the `entrypoint`
script exists before creating the tag. This is caused by [the `case` block, that checks the `log`
for the SemVer bump, defaults to exiting when `DEFAULT_BUMP` is none](https://github.com/anothrNick/github-tag-action/blob/3840ec22ac98e14d981375e3ae2d8d0392964521/entrypoint.sh#L112) which happens
before [the `CUSTOM_TAG` is evaluated](https://github.com/anothrNick/github-tag-action/blob/3840ec22ac98e14d981375e3ae2d8d0392964521/entrypoint.sh#L139).

**Comment by sammcj** [comment]
Hello - is this still an issue with v1.45.0 and required?

**Comment by sbe-arg** [comment]
Has been resolved, please reopen if necesary
