### ISSUE TITLE
Add output for new tag

### ISSUE THREAD

**Issue by DarmawanEfendi** [anothrNick/github-tag-action#16]
Hi @anothrNick ,

Thanks for  this tag action. it's great and I used it on my project.
But it would be nice to add 1 line code for set output value ?
`echo ::set-output name=NEW_TAG::$new`
So I can grab the new version of tag on another step.

Thanks.

**Comment by anothrNick** [comment]
Hi @DarmawanEfendi, I'm glad you're finding this action useful!

This is a great idea, thanks for creating the issue. I've attempted to implement this with https://github.com/anothrNick/github-tag-action/pull/17, please review when you have time.

Thanks!

**Comment by anothrNick** [comment]
This improvement is now available in `1.7.1`
