### ISSUE TITLE
Don't rebuild docker image every time

### ISSUE THREAD

**Issue by Hades32** [anothrNick/github-tag-action#163]
Replacing the Dockerimage with a single `FROM pre-built-image` reduces the action runtime from ~13s to 2s for me. Would be a good idea to just split the Dockerfile in a build and a run version

Changed this in my fork: https://github.com/Hades32/github-tag-action

**Comment by sammcj** [comment]
I'll create a workflow that builds and publishes the container image on a schedule, then update the Action to use said image.

**Comment by sbe-arg** [comment]
@Hades32 do you mind opening a PR? I like the approach.

**Comment by sammcj** [comment]
I've got this on my list of things to do this week - hopefully I get time 😅

**Comment by sammcj** [comment]
Working on this now

**Comment by sammcj** [comment]
Anyone every try this out by chance?

**Comment by sammcj** [comment]
Well I had a crack but hit permissions problems that I didn't seem to hit in my fork, I'm assuming @anothrNick might need to change some repo settings perhaps to enable the container image registry?

https://github.com/anothrNick/github-tag-action/actions/runs/3625552268/jobs/6113716979#step:7:292

**Comment by shachar-karry** [comment]
This works well from the fork and gets you from 20s to 6s.
Hope it makes it into anothrNick/github-tag-action

**Comment by sammcj** [comment]
I've carved out some time to work on this next week in case I don't get to it between other work this week.

**Comment by sbe-arg** [comment]
I spend a few hours on this over the weekend and my thoughts are that the nature of this action is to build the image each time. Is gonna be harder point each dockerfile image to the corresponding point in time tag during release time.

if we build a versioned docker image from the docker file it tills have to be referenced back in here https://github.com/anothrNick/github-tag-action/blob/master/action.yml#L4-L6 and here https://github.com/anothrNick/github-tag-action/blob/master/Dockerfile#L1 for 10 seconds speed gains? I think after building the image the complexity really starts in how to pass the right version dynamically on the fly.

I vote for closing this.

**Comment by sammcj** [comment]
Yeah fair enough, it should probably be rewritten as a TS action anyway tbh.
