### ISSUE TITLE
1.39.0 release creating only v tag

### ISSUE THREAD

**Issue by akhileshlamba02** [anothrNick/github-tag-action#166]
Hi,
Can anyone please have a look at the issue that I'm facing.

Latest version is not creating semVer tag properly. It only creates v tag. Below is my configuration:
*** CONFIGURATION ***
	DEFAULT_BUMP: patch
	WITH_V: true
	RELEASE_BRANCHES: master,main
	CUSTOM_TAG: 
	SOURCE: .
	DRY_RUN: false
	INITIAL_VERSION: 1.0.0
	TAG_CONTEXT: repo
	PRERELEASE_SUFFIX: beta
	VERBOSE: true

**Error:**
pre-patch
Bumping tag . 
	New tag v
fatal: tag 'v' already exists

It also throws this error:
**fatal: ambiguous argument 'multiple': unknown revision or path not in the working tree.**

But when I use the previous release 1.36.0. It works properly.

Thanks!

**Comment by sammcj** [comment]
Having the same problem, any update on a fix @anothrNick ?

**Comment by arpanrec** [comment]
Same issue

**Comment by cruftyoldsysadmin** [comment]
Having the same problem with anything after 1.36.0.

**Comment by dgokcin** [comment]
same issue. any fix coming soon?

**Comment by sbe-arg** [comment]
we are blocked to merge this https://github.com/anothrNick/github-tag-action/pull/157 wich fixes most of latest problems
but I cannot self merge while im a maintained I need another maintainer to approve me

**Comment by sammcj** [comment]
While I can approve #157 , I can't merge it, @anothrNick are you able to approve / merge?
