### ISSUE TITLE
Multiple workflows in diffrent paths

### ISSUE THREAD

**Issue by klausgls** [anothrNick/github-tag-action#170]
Can you get a diffrent number pool, for path based project builds, it seems you can only get from the main pool?

**Comment by sbe-arg** [comment]
https://github.com/anothrNick/github-tag-action/pull/157

**Comment by sammcj** [comment]
This should be resolved now, if not let me know and I'll reopen.

**Comment by klausgls** [comment]
It's not working its still using the same tag.
 * [new branch]      main                 -> origin/main
 * [new tag]         1.0.10               -> 1.0.10
 * [new tag]         1.0.11-beta.1        -> 1.0.11-beta.1
 * [new tag]         1.0.11-beta.10       -> 1.0.11-beta.10
 * [new tag]         1.0.11-beta.11       -> 1.0.11-beta.11
 * [new tag]         1.0.11-beta.12       -> 1.0.11-beta.12
 * [new tag]         1.0.11-beta.13       -> 1.0.11-beta.13
 * [new tag]         1.0.11-beta.14       -> 1.0.11-beta.14
 * [new tag]         1.0.11-beta.15       -> 1.0.11-beta.15
 * [new tag]         1.0.11-beta.16       -> 1.0.11-beta.16
 * [new tag]         1.0.11-beta.17       -> 1.0.11-beta.17
 * [new tag]         1.0.11-beta.18       -> 1.0.11-beta.18
 * [new tag]         1.0.11-beta.19       -> 1.0.11-beta.19
`


Just to clear up what it is im trying to get to work. Keep in mind both .net project are in the repository in diffrent folders and i want to have for instance 1.0.1 in workflow1.yaml (it has been run 2 times) and 1.0.3 in workflow2.yaml (when it has been run 4 times and workflow1 has run 2 time) i hope it makes sense.

workflow1.yaml
`
name: LabelAPI.User.Console
on:
  pull_request:
    paths:
      - src/LabelApi.User.Console/**
`
workflow2.yaml
`
name: LabelAPI.RoutingData.Console

on:
  pull_request:
    paths:
      - src/LabelApi.RoutingData.Console/**
`

**Comment by sammcj** [comment]
Hello,

That is an old version of the action, can you please try with:

1. github-tag-action@1.45.0
2. actions/checkout@v3

**Comment by klausgls** [comment]
it creates a funny output

`
Run anothrNick/github-tag-action@1.45.0
/usr/bin/docker run --name f70fae1425ac00d4574834548b[6](https://github.com/gls-denmark/peak-labelapi/actions/runs/3049254683/jobs/4915138674#step:4:7)4e9dafa6_[7](https://github.com/gls-denmark/peak-labelapi/actions/runs/3049254683/jobs/4915138674#step:4:8)09d[8](https://github.com/gls-denmark/peak-labelapi/actions/runs/3049254683/jobs/4915138674#step:4:9)4 --label 817f70 --workdir /github/workspace --rm -e "GITHUB_TOKEN" -e "INITIAL_VERSION" -e "DEFAULT_BUMP" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/peak-labelapi/peak-labelapi":"/github/workspace" 817f70:fae1425ac00d4574834548b64e[9](https://github.com/gls-denmark/peak-labelapi/actions/runs/3049254683/jobs/4915138674#step:4:10)dafa6
fatal: detected dubious ownership in repository at '/github/workspace'
*** CONFIGURATION ***
To add an exception for this directory, call:
	DEFAULT_BUMP: patch

	WITH_V: false
	git config --global --add safe.directory /github/workspace
	RELEASE_BRANCHES: master,main
fatal: detected dubious ownership in repository at '/github/workspace'
	CUSTOM_TAG: 
	SOURCE: .
	DRY_RUN: false
	INITIAL_VERSION: 1.0.0
	TAG_CONTEXT: repo
	PRERELEASE_SUFFIX: beta
	VERBOSE: true
pre_release = true
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
fatal: detected dubious ownership in repository at '/github/workspace'
No new commits since previous tag. Skipping...
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
fatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
fatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
fatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
fatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace`

**Comment by sammcj** [comment]
It looks like you haven't checked out the repo first,

```
 fatal: detected dubious ownership in repository at '/github/workspace'
```

I think it should be run in something like `/github/workspace/my-repo`

**Comment by sammcj** [comment]
The workspace issue specifically might be resolved by https://github.com/anothrNick/github-tag-action/pull/183

**Comment by sammcj** [comment]
Can you try again with 1.46.0?

**Comment by sbe-arg** [comment]
Closing pleease reopen if necesary
