### ISSUE TITLE
Release branch wildcard .* broken

### ISSUE THREAD

**Issue by aarontwf** [anothrNick/github-tag-action#178]
Seems like the action no longer respects wildcards in recent versions. Could be related to this change https://github.com/anothrNick/github-tag-action/commit/e4d41c448cce9a0e6b9f4a9a10960e336fe20b6e.

Before (1.39.0)
```
*** CONFIGURATION ***
	DEFAULT_BUMP: patch
	WITH_V: true
	RELEASE_BRANCHES: .*
	CUSTOM_TAG: 
	SOURCE: .
	DRY_RUN: true
	INITIAL_VERSION: 0.0.0
	TAG_CONTEXT: repo
	PRERELEASE_SUFFIX: beta
	VERBOSE: false
Is .* a match for HEAD
pre_release = false
patch
Bumping tag v1.56.0. 
	New tag v1.56.1
```

With 1.40.0
```
*** CONFIGURATION ***
	DEFAULT_BUMP: patch
	WITH_V: true
	RELEASE_BRANCHES: .*
	CUSTOM_TAG: 
	SOURCE: .
	DRY_RUN: true
	INITIAL_VERSION: 0.0.0
	TAG_CONTEXT: repo
	PRERELEASE_SUFFIX: beta
	VERBOSE: false
pre_release = true
Setting beta pre-tag . With pre-tag v1.56.2-beta.0
```

**Comment by Fuerback** [comment]
The change which causes it seems to be this one https://github.com/anothrNick/github-tag-action/compare/1.39.0...1.40.0#diff-6f9d41d046756f0ddc2fcee0626bdb50100d12b88f293734eff742818e03efa2L40

**Comment by sbe-arg** [comment]
Whats the use case for branches=`.*` ?

**Comment by sbe-arg** [comment]
Gonna work on this this week.

**Comment by sbe-arg** [comment]
@Fuerback https://github.com/anothrNick/github-tag-action/pull/190

**Comment by sbe-arg** [comment]
@Fuerback please test the latest version `1.49.0` and report back, will close in the meantime

**Comment by Fuerback** [comment]
Thanks @sbe-arg, using [1.51.0](https://github.com/anothrNick/github-tag-action/releases/tag/1.51.0) and it's working just fine now
