### ISSUE TITLE
Better manage the Pull Request case

### ISSUE THREAD

**Issue by fabricepipart** [anothrNick/github-tag-action#18]
Hi
You project is great and I have been looking for something similar for quite some time. I have always been surprised that nobody tackled the automation of the computation of version numbers.
I was about to build mine when I saw your project.

I tried it but I am still missing a few features. Mainly to distinguish tags from the main branch and from other branches I'd be glad to contribute if you accept.

What I am mainly missing is a way to create pre-releases. This would apply mainly in the case of Pull Requests. The idea would be to pass an input (PRE-RELEASE) and in that case, the computation would be the following:
* last tag would filter all pre-releases
* version would be bumped as usual
* patch version would be forced to 0
* version would be postfixed : -SHA where SHA is the short version of the sha of the commit.

Can you tell me what you think?

Best regards

**Comment by anothrNick** [comment]
Hi @fabricepipart, thanks for submitting this.

What your are proposing sounds like a great enhancement, I just want to make sure I understand the use case.

Basically, you want to be able to run this action on any and all Pull Requests, and push a pre-release tag for the PR commit (following the tag creation logic you've listed above.). Am I understanding correctly?

**Comment by fabricepipart** [comment]
You got it perfectly right. That's because I want to generate a (ideally meaningful semver) version number for the artefacts that are built during the PR.
I actually build artefacts that I run on a staging environment. And then I also shoot some tests on that environment. As a consequence, I need to version both the built artefacts and the tests.

I tried that workflow with your github action "as-is". But I ended up with a confusion of what were "temporary tags" and the minor of master got bumped as soon as a PR was built.

**Comment by fabricepipart** [comment]
If you're interested by the proposal, give me a bit more time before merging, honestly I did not even test it yet.

**Comment by anothrNick** [comment]
Ok neat, sounds good. Instead of using an ENV VAR to signal the pre-release, you could probably automatically trigger the pre-release logic by checking which event triggered the action. You can find the event by parsing the event payload, similar to how we get the Ref API URL here: https://github.com/anothrNick/github-tag-action/blob/master/entrypoint.sh#L51.

Merge should be the `PushEvent`: https://developer.github.com/v3/activity/events/types/#pushevent

PR should be the `PullRequestEvent`: https://developer.github.com/v3/activity/events/types/#pullrequestevent

If you can identify which event triggered the action, I think we can safely assume someone wants the pre-release tag without added workflow configuration.

**Comment by fabricepipart** [comment]
If we do it that way, there is another use case that would not be covered: the feature branch. This one would bump the version and the confusion with the release branch (ie usually `master`) would remain.

**Option 1:**
With a something like:
```
      env:
        PRE_RELEASE: ${{ github.ref == 'refs/heads/master' }}
```
the user defines what branch(es) should generate releases. This is probably the most flexible but I start thinking you're right, it makes the configuration a bit too complicated. It would be worth it if we could have several branches that generate releases. As of today, since the _latest tag_ is necessarily the one we bump, it is not worth it probably.

**Option 2:**
No configuration like you propose. The simplest and solves the PR case.

**Option 3:**
Based on Option 2 but with one additional optional configuration: `RELEASE_BRANCHES`. By default it would be master and it would be the preparation for Option 4. Parameter could even be hidden for the time being.
When it is a `PushEvent` on a branch that does not match any of the RELEASE_BRANCHES patterns, we treat it like a pre-release.

**Option 4:**
In the future, I could help introduce a mechanism where we bump the _latest tag_ of the **current (or destination) branch**. It is a bit more complex but certainly worth it in terms of flexibility.
This way , you can have all kind of branches that evolve independently. For example:
* `master`: `3.4.5`, `3.6.0` ...
* `release/1` : `1.0.3`, `1.1.0`...
* `release/2.1` : `2.1.3`, `2.1.4`...
* `release/2.2` : `2.2.0`, `2.2.1`...
This requires looking for the latest tag of _that_ branch.
But let's keep that for later!

Would option 3 be OK?

**Comment by fabricepipart** [comment]
I amended the PR to implement option 1 :
https://github.com/fabricepipart/github-tag-action/blob/feature/prerelease/entrypoint.sh

I proposed here a version where you can specify a release branch:
https://github.com/fabricepipart/github-tag-action/blob/feature/prerelease-mode2/entrypoint.sh

I proposed here a version where you can specify one or more release branches
https://github.com/fabricepipart/github-tag-action/blob/feature/prerelease-mode3/entrypoint.sh

Tell me what you prefer!

**Comment by anothrNick** [comment]
I think your proposal for Option 3 makes sense. I like the idea of an iterative approach to Option 4. As long as it's implemented without breaking changes (I've noticed most projects using this action are pointing at `master`... which is my fault since that's what the examples have 😄 ), I think it's a great improvement. 👍

Feel free to submit a PR with your changes for Option 3.

**Comment by fabricepipart** [comment]
Here you are! https://github.com/anothrNick/github-tag-action/pull/21

**Comment by anothrNick** [comment]
@fabricepipart Your contribution is present in https://github.com/anothrNick/github-tag-action/tree/1.8.0. I've just published 1.8.0 to the actions marketplace. Thanks again!

**Comment by fabricepipart** [comment]
I saw that! I just updated my usage of your plugin. I really appreciated the way the contribution was received (quick feedback, guidance, justified opinions, etc...). I hope I'll find the time to contribute more!

**Comment by anothrNick** [comment]
Looking forward to it!
