### ISSUE TITLE
Latest change (1.45.0) is causing the "fatal: detected dubious ownership in repository at '/github/workspace' 11" bug.

### ISSUE THREAD

**Issue by antroy-xlab** [anothrNick/github-tag-action#181]
A change yesterday is causing the tagging action to fail with: `fatal: detected dubious ownership in repository at '/github/workspace'
11`

I believe it is due to the change in 1.45.0 which narrows the scope of the `git config --global --add safe.directory` line.

In addition, I would have expected that action to actually fail in this case, but instead it displays the error, but does not tag the code and continues with the workflow masking the root cause of the issue.

**Comment by johnykov** [comment]
same story on my side I had to downgrade to 1.40.0

**Comment by haooliveira84** [comment]
Same here! I had to downgrade to 1.42.0

**Comment by arnested** [comment]
Downgrading to 1.44.0 was sufficient for me.

**Comment by sammcj** [comment]
yikes! OK another test case needs to be added for this!

Going to revert in https://github.com/anothrNick/github-tag-action/pull/183
