### ISSUE TITLE
Add/Improve tests

### ISSUE THREAD

**Issue by sammcj** [anothrNick/github-tag-action#184]
We should add and improve the tests to cover more failure scenarios / known working configuration patterns.

We should test to cover things like:

- https://github.com/anothrNick/github-tag-action/issues/182
- https://github.com/anothrNick/github-tag-action/issues/181
- https://github.com/anothrNick/github-tag-action/issues/170

etc....

**Comment by sammcj** [comment]
@sbe-arg this is needed more than ever 🤣

**Comment by sbe-arg** [comment]
Yeah hahaha, We need some sort of current schema config so we can compare input with desired outputs.

**Comment by sammcj** [comment]
I think it'd be good to have a separate PR for adding general / current tests as looking at that PR there's been some back and forth and it's rather large - which is risky to merge... without better tests 😄
