### ISSUE TITLE
Prerelease tag for Pull Requests

### ISSUE THREAD

**Issue by dkirrane** [anothrNick/github-tag-action#192]
Is it possible to create prerelease tags for PRs using `${{ github.event.pull_request.number }}`

e.g. for each new commit to Pull Request 20
```
0.0.0-pr20.1
0.0.0-pr20.2
0.0.0-pr20.3
```

or maybe an option to re-create the tag on each commit to the Pull Request branch.
e.g. each new commit to pr 20 this tag gets re-created `0.0.0-pr20`

**Comment by sbe-arg** [comment]
I dont see why not. I mean as is now it should work for some of the examples you mentioned.
Making a tag per commit will depend of the overall workflow configuration not necesarely this action settings as long there are changes between commits should do it.

Try using `PRERELEASE_SUFFIX: ${{ github.event.pull_request.number }}` you need to make the job to run on euther pull request update depending use case that should give you the pr20.1 pr20.2 pr20.3 etc.

As for doing this using non pre release tags then not implemented as feature yet.
