### ISSUE TITLE
Intermittent invalid reference format

### ISSUE THREAD

**Issue by TheNavigateur** [anothrNick/github-tag-action#193]
Every so often I get this:

`Invalid argument "***.dkr.ecr.eu-west-1.amazonaws.com/my-org/my-service:" for "-t, --tag" flag: invalid reference format`

...during a Github Action. When I retry the issue goes away, so it is intermittent.

I'm using version 1.36.0.

**Comment by sbe-arg** [comment]
@TheNavigateur can you try using the latest version and if you can sharing with us a log blop?
