### ISSUE TITLE
Convert set-output to use GITHUB_OUTPUT file

### ISSUE THREAD

**Issue by JP-Dhabolt** [anothrNick/github-tag-action#205]
Due to a change on the Github side on 10/11, the use of `set-output` [is now deprecated and will be disabled "soon"](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).  Instead, the action should append to the file designated with the environment variable `GITHUB_OUTPUT`.

As an example:
`echo "::set-output name=new_tag::$tag"` would be converted to `echo "new_tag=$tag" >> $GITHUB_OUTPUT`

**Comment by sbe-arg** [comment]
@JP-Dhabolt thanks for raising this.

**Comment by Sandra-headscape** [comment]
https://github.com/anothrNick/github-tag-action/pull/206#issuecomment-1297365668
> am currently using 1.52.0, but upon checking realised this wasn't released as a new version as the build failed - https://github.com/anothrNick/github-tag-action/actions/runs/3372412451/jobs/5595804270

can I still use the updated version? thanks (:

**Comment by floriancircly** [comment]
Hi, i am using 1.52.0 and i still get the GitHub error "Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files.".
