### ISSUE TITLE
Monorepo usage

### ISSUE THREAD

**Issue by LjuboDaon** [anothrNick/github-tag-action#208]
Hi,

We are looking into GHA that can automate our versioning for monorepo, we have multiple projects inside one repository.
This library is good for us, unless I don't know if it can support prefixes or something that can distinguish multiple projects.
```
frontend/v1.2.1
backend/v1.5.6
```

Can someone helps us with this issue or give us an idea?

Thanks

**Comment by sbe-arg** [comment]
I would probably build packages and base versioning from source file instead of tags for a branch.

Closing this

**Comment by berkayerten** [comment]
If I'm interpreting @sbe-arg's suggestion correctly, the recommendation is to increase the versions directly within each module's source code. From what I understand, the aim of this project is to automate the incrementation of Git tags, a feature that would also be highly beneficial for **monorepo** projects, as pointed out by @LjuboDaon.

**Comment by berkayerten** [comment]
Thank you for your reply and suggestion @sbe-arg! Your solution looks insightful. I will have a look into it!
