### ISSUE TITLE
GitHub Actions: Deprecating save-state and set-output commands

### ISSUE THREAD

**Issue by stevegaunt** [anothrNick/github-tag-action#217]
when setting the tag, setOutput is being used in the entrypoint.sh

starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error.

example warning when GitHub action is run

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by sbe-arg** [comment]
This has been implemented in master but the merge/tag bumping has been broken hence users are not seeing the fix.

**Comment by sbe-arg** [comment]
This has been implemented in master but the merge/tag bumping has been broken hence users are not seeing the fix.
