### ISSUE TITLE
Failed build in latest commit causes issues when pulling from master

### ISSUE THREAD

**Issue by PetaPetaPeta** [anothrNick/github-tag-action#221]
The latest commit to master  in this repository appears to have failed when being pushed to the docker registry. https://github.com/anothrNick/github-tag-action/actions/runs/3617593707/jobs/6096586545

This breaks the usage of the master master branch as shown in the screenshot below:
![image](https://user-images.githubusercontent.com/2445709/205651118-e6c78f5d-70e8-4e03-aab7-2fb42d8b0983.png)

**Comment by sammcj** [comment]
@sbe-arg can you please approve the revert https://github.com/anothrNick/github-tag-action/pull/220

**Comment by sammcj** [comment]
Fixed via #220
