### ISSUE TITLE
merge commit message ignored

### ISSUE THREAD

**Issue by KonstantinKlepikov** [anothrNick/github-tag-action#227]
i use 1.55.0 - no matter what i wrote in any commits - is ignored #patch, #minore, #major and is used default

[source of problem](https://github.com/KonstantinKlepikov/cold-war-boardgame/blob/main/.github/workflows/release.yml)

**Comment by sbe-arg** [comment]
i think relates to issue #227 default branch filter

Are you using a non master default branch?

**Comment by sbe-arg** [comment]
Closing please re-open if the problem persists on 1.56
