### ISSUE TITLE
Hard coded branch name for getting full git history results in broken action

### ISSUE THREAD

**Issue by TobiWo** [anothrNick/github-tag-action#229]
[Here](https://github.com/anothrNick/github-tag-action/blob/master/entrypoint.sh#L130) you hard code `master` as branch to check for full history. However, if your `main` branch is called `main` or differently this will not work. You have multiple options:
* add a new environment variable where the user set's the name of the main branch
* maybe use the already present `RELEASE_BRANCHES` env variable but this is maybe a bit greedy ... I mean how to decided which is the main branch if multiple release branches are defined
* or you extract the default branch ([see here](https://stackoverflow.com/questions/28666357/how-to-get-default-git-branch)) assuming that this is the users main/master which should be the case

For reference: https://github.com/TobiWo/eth-duties/actions/runs/3765394398/jobs/6400825949#step:4:33

**Comment by sbe-arg** [comment]
Good point @sammcj mind opening a hotfix pr I'm on holidays without access to a laptop

Maybe we can set it to something like

`${{ github.event.repository.default_branch }}`

And apologies

**Comment by sbe-arg** [comment]
Oh wait I see what you mean this breaks the
Full history Line 130 master..HEAD

**Comment by sbe-arg** [comment]
Did this over the phone needs testing before merging

https://github.com/anothrNick/github-tag-action/pull/230

**Comment by sbe-arg** [comment]
hotfix merged @TobiWo can you test 1.56 and re-open if the problem persists

**Comment by TobiWo** [comment]
I will test it. Thanks.

**Comment by TobiWo** [comment]
> hotfix merged @TobiWo can you test 1.56 and re-open if the problem persists

Hi @sbe-arg, I tested the new release but still have some issues.

1. If I `rebase and merge` the action doesn't recognize any commit with `BRANCH_HISTORY: full` (see [here](https://github.com/TobiWo/test-github-actions/actions/runs/3836732664/jobs/6531223026))
2. If I `rebase and merge` everything works as expected with `BRANCH_HISTORY: last` (see [here](https://github.com/TobiWo/test-github-actions/actions/runs/3836769528/jobs/6531301252))
3. If I use a regular `merge commit` I receive a similar error as before the fix (see [here](https://github.com/TobiWo/test-github-actions/actions/runs/3836831587/jobs/6531615496))

I'm not able to re-open the issue (maybe I don't see how or I don't have permissions). In any way this needs some fix.
It would be nice if the full commit history can be considered also on `rebase and merge`. I like to use the rebase approach and I always need to check the last commit message for the respective keyword currently which is a bit cumbersome.

**Comment by sbe-arg** [comment]
Reopened for tracking...

Its been looked in combination to fixing the history and default branch setting.

They both depend on each other depending the type of history and the alpine container has no head but workarounds are comming.

**Comment by sbe-arg** [comment]
Tracking in #243
