### ISSUE TITLE
Question: Shouldn'tVersion 1.58 should have been a major release?

### ISSUE THREAD

**Issue by dgokcin** [anothrNick/github-tag-action#236]
Hello

I have been using this action on pushes to my main branches and using the bumped version output in many places like tagging production docker images, publishing release notes etc. I was using the action with @v1 tag to get the latest non-breaking updates. 

This morning, I had to update 40+ repositories and add the DEFAULT_BRANCH option to every single one of them because all of a sudden the most critical workflows in my repos which are the deployment workflows, this action started to fail. Thats why I believe the latest version should have been a breaking change.

How should I configure my workflows so that I do not have to live through this again?

Thanks.

**Comment by jalavosus** [comment]
I pinned the version of `gihub-tag-action` in my workflow files to `1.55.0`, ex:

```yaml
- name: Bump Tag
   uses: anothrNick/github-tag-action@1.55.0
```

**Comment by dgokcin** [comment]
@jalavosus We used to use this action like that. Than all of a sudden github changed something in their api and this action stopped working. I believe it was #181

**Comment by sbe-arg** [comment]
Okay so DEFAULT_BRANCH is not working for you either are you using squash? See issue #232

Ill try to do some more deep testing on this today.

Apologies.
I the meantime can you share the runner logs in debug mode of the broken workflows?

**Comment by sbe-arg** [comment]
1.55 could have been major but is a cascading of events that come from a problem in 1.47 was hard to define it as v2. We are considering reverting from default full back to default last due squash vs non squash log capture differences.

For now if you are using squash stick to using logs last.

**Comment by dgokcin** [comment]
@sbe-arg I believe what I am having is caused because of this. #230

**Comment by sbe-arg** [comment]
And what workflow do you use is squash? Or commit merge.

The full log does not currently work when using squash merge with rebase for example as discussed in issue #232 hence the full_squash option and option to set as default the last instead of full introduced in 1.55

**Comment by dgokcin** [comment]
@sbe-arg I am not using squash, I am using merge commits.

**Comment by sbe-arg** [comment]
https://github.com/anothrNick/github-tag-action/pull/237 we are gonna switch to a different log strategy as proposed by @jonavos in #232 I tested this with rebase and squash and seems to work when using compare but definitely broken on full due the HEAD comparison

**Comment by sbe-arg** [comment]
Gonna close this one as we are tracking in #243

**Comment by sulranjan** [comment]
sultanjanmagrio110@gmail.com

[](![Image](https://github.com/user-attachments/assets/ff4a3b30-6f49-4729-8c11-3a122219e026)/[](url))
