### ISSUE TITLE
Error exit when DEFAULT_BRANCH is empty, despite BRANCH_HISTORY being set to last

### ISSUE THREAD

**Issue by vancejc-mt** [anothrNick/github-tag-action#243]
Hello,

It looks like https://github.com/anothrNick/github-tag-action/pull/235 introduced an issue for us (as mentioned in the PR) - in our case, we have `BRANCH_HISTORY` set to `last`, but it's still erroring out due to `DEFAULT_BRANCH` being empty.

While theoretically `DEFAULT_BRANCH` should not be empty (looks like there's an issue with the symbolic-ref in our remote pointing to a non-existent branch (thanks `main`/`master`)), the fact that we're using `BRANCH_HISTORY` set to `last` should ignore this exit error altogether - `DEFAULT_BRANCH` is not used at all if `BRANCH_HISTORY` is set to `last`.

Is there a way that we can avoid the `DEFAULT_BRANCH` check if `BRANCH_HISTORY` is set to `last` ?

**Comment by sbe-arg** [comment]
The quickest fix is to set the env var DEFAULT_BRANCH with whatever is the default branch, main master, other

**Comment by sbe-arg** [comment]
Can you share the debug logs as well and what merge strategy are you using?

**Comment by stefano-elysium** [comment]
having the same issue, please fix ASAP

**Comment by sbe-arg** [comment]
@stefano-elysium can you please share the debug logs. Hard to understand why the var is empty for your use case without logs.

**Comment by vancejc-mt** [comment]
Agree we can put in the `DEFAULT_BRANCH` to avoid this (doing so now) but shouldn't technically be necessary with `last` (I saw your PR go in which should avoid this - awesome thanks!)

Debug logs:
```
The DEFAULT_BRANCH should be autodetected when tag-action runs on on PRs else must be defined, See: https://github.com/anothrNick/github-tag-action/pull/230, since is not defined we find it natively
fatal: ref refs/remotes/origin/HEAD is not a symbolic ref
default_branch=
Error: DEFAULT_BRANCH must not be null, something has gone wrong.
```

Let me know if I can get you information otherwise.

**Comment by vancejc-mt** [comment]
Our merge strategy is a little complex; we have `main` and `dev` branches which are long lived.  Feature branches off of `dev` are squashed-merged into `dev`, and when ready to release we do a normal merge to `main`.  Our action only queues on `push` to `main`.

**Comment by sbe-arg** [comment]
Thanks for sharing the merge strategy details.
Will merge as soon another maintainer approves it.

**Comment by vancejc-mt** [comment]
Things look like they're working, thanks again

**Comment by TobiWo** [comment]
Hi @sbe-arg, I also tested the new version but still found some issues:

I always use the rebase and merge pattern with the following workflow trigger:

```
on:
  pull_request:
    types:
      - closed
    branches:
      - main
```

1. If I set `BRANCH_HISTORY: full` and add `ref: ${{ github.sha }}` to the `with` property (as suggested in your documentation) I receive a `fatal: ambiguous argument` error. [Here is an example run.](https://github.com/TobiWo/test-github-actions/actions/runs/3881983060/jobs/6621599569)
2. If I set `BRANCH_HISTORY: full` without `ref: ${{ github.sha }}` in the `with` property, the commit history is empty so no version bump happens (`DEFAULT_BUMP: none`). [Here is an example run.](https://github.com/TobiWo/test-github-actions/actions/runs/3882015969/jobs/6621668848)
3. If I set  `BRANCH_HISTORY: last` without `ref: ${{ github.sha }}` in the `with` property (as suggested in your documentation) everything works as expected. [Here is an example run.](https://github.com/TobiWo/test-github-actions/actions/runs/3882036243/jobs/6621712335)

**Comment by sbe-arg** [comment]
Whats the problem then? Documentation in the readme?

Cc @sammcj

**Comment by TobiWo** [comment]
I would say the issue is the documentation (see fatal error) and how the tool works on rebase and merge in general. The full commit history check does not work if I rebase and merge. I didn't test with normal merge commit workflow but I guess as most users use this pattern (I guess you as well) you would have seen many people complaining 🙂.

**Comment by sbe-arg** [comment]
Mind opening a pr with the readme improvements? @TobiWo

**Comment by TobiWo** [comment]
Hi @sbe-arg sorry for the super late reply. However, I just want to comment on your request: I'm working on my own open source tool like you guys so I actually do not have time to work here as well (although I really like this action). If I will try to improve the `rebase and merge` functionality if I can find time and maybe adapt the documentation as requested.
