### ISSUE TITLE
Sequentially workflow

### ISSUE THREAD

**Issue by shaypi** [anothrNick/github-tag-action#249]
When I am using anothrNick/github-tag-action@1.55.0 in my workflow its break Sequentially order and cause an issue with pulling an images from Docker Hub

The workflow the following in my workflow order:
1. Checkout
2. Login to docker hub(paid account - **unlimited pulls** )
3. Running compose 
4. Using tag - anothrNick/github-tag-action

but from some reason my actions starts with **Using tag**  and cause the following error:
```
Build container for action use: '/runner/_work/_actions/anothrNick/github-tag-action/1.55.0/Dockerfile'.
  /usr/local/bin/docker build -t 60e[2](https://url/org/repo/runs/16087?check_suite_focus=true#step:3:2)26:5720[3](https://url/org/repo/runs/16087?check_suite_focus=true#step:3:3)0970eb9[4](https://url/org/repo/runs/16087?check_suite_focus=true#step:3:4)1c08be3f8[5](https://url/org/repo/runs/16087?check_suite_focus=true#step:3:5)351[6](https://url/org/repo/runs/16087?check_suite_focus=true#step:3:6)82e[7](https://url/org/repo/runs/16087?check_suite_focus=true#step:3:7)[8](https://url/org/repo/runs/16087?check_suite_focus=true#step:3:8) -f "/runner/_work/_actions/anothrNick/github-tag-action/1.55.0/Dockerfile" "/runner/_work/_actions/anothrNick/github-tag-action/1.55.0"
  #1 [internal] load .dockerignore
  #1 sha256:420318c0fbac72d300c[9](https://url/org/repo/runs/16087?check_suite_focus=true#step:3:9)de51dcbe988225f470e9ee502874bbed78f6538f147d
  #1 transferring context: 2B done
  #1 DONE 0.1s
  
  #2 [internal] load build definition from Dockerfile
  #2 sha256:7bb674195ce9f2b32c1cd4a053cec1b80a6ac9caf[13](https://url/org/repo/runs/16087?check_suite_focus=true#step:3:13)c44268b5187ea0c133cf3
  #2 transferring dockerfile: 368B done
  #2 DONE 0.1s
  
  #3 [internal] load metadata for docker.io/library/node:16-alpine
  #3 sha256:93febbdbcf5a756e6e084d46d56976a0630ae35cc38d744d3fb69ab9a7ce9b20
  #3 ERROR: failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/node/manifests/sha256:95a849eafc573ad0d972fd67c569369e7aa94d55a21ede3b972e3137e5f8e43a: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
  ------
   > [internal] load metadata for docker.io/library/node:[16](https://url/org/repo/runs/16087?check_suite_focus=true#step:3:16)-alpine:
  ------
```

**Comment by sbe-arg** [comment]
Can you share your workflow yaml file?

Sorry the delay responding to this.

Still looks like a credentials problem.

**Comment by shaypi** [comment]
# for some nice emojie https://emojipedia.org/
---
    name: xxxx JAR Assemble And Build
    on:
      pull_request:
      workflow_dispatch:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    env:
      REGISTRY: containers.github.xxxx.com/
    jobs:
      
      cicd:
        if: ${{ !startsWith(github.event.pull_request.base.ref, 'staging') && !startsWith(github.event.pull_request.base.ref, 'master') && !startsWith(github.event.pull_request.base.ref, 'development') }}
        # if: ${{ github.event.pull_request.base.ref == 'cicd' }}
        name: xxx
        environment: cicd
        runs-on: xxx-runner-deployment
        timeout-minutes: 60
        steps:
        - name: ⬇️ Checkout xxx
          uses: actions/checkout@v3
          with:
            repository: xxx/xxx
            ref: ${{ github.head_ref }}
            token: ${{ secrets.GH_PAT }}
        
        - name: ⚙️ running compose
          working-directory: .ci
          run: |
            echo "Running MONGO container in detached mode"
            docker-compose --file testsmongo-compose.yml up --detach --remove-orphans
            echo "Runnning SBT image"
            docker-compose --file buildsbtdocker-compose.yml up --abort-on-container-exit
            exit_code=$?
            if [ $exit_code -ne 0 ]; then
              exit $exit_code
            fi
            echo "Building xxxx-storage docker image"

        - name: 👀 Tag
          # if: github.event.pull_request.merged == true
          id: autotagger
          uses: anothrNick/github-tag-action@1.55.0
          env:
            GITHUB_TOKEN: "${{ secrets.GH_PAT }}"
            WITH_V: true

        - name: echo Tag
          run: echo ${{ steps.autotagger.outputs.tag }}

        - name: 🐱‍🚀 Release
          id: create_release
          if: steps.autotagger.outputs.tag != ''
          uses: actions/create-release@v1.1.4
          env:
            GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          with:
            tag_name: ${{ steps.autotagger.outputs.tag }}
            release_name: Version ${{ steps.autotagger.outputs.tag }}
            draft: false
            prerelease: false
        
        - name: 🔑 Login to AWS
          run: aws ecr get-login-password | docker login --username AWS --password-stdin xxxx.dkr.ecr.eu-west-1.amazonaws.com

        - name: 🔑 Log in to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.xxxx.com
            username: ${{ github.actor }}
            password: ${{ secrets.GH_PAT }}
        
        - name: 🐳 Build, tag, and push image to Amazon ECR
          env:
            App: airflow_xxxx_storage
            ECR_REGISTRY: xxxx.dkr.ecr.eu-west-1.amazonaws.com
            ECR_REPOSITORY: microservices
            IMAGE_TAG:  ${{ github.sha }}
          run: |
            docker build -t airflow_xxxx_storage -f .ci/Dockerfile .
            docker tag $App $ECR_REGISTRY/$ECR_REPOSITORY:$App-$IMAGE_TAG
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$App-$IMAGE_TAG
            docker tag $App $ECR_REGISTRY/$ECR_REPOSITORY:$App
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$App
            docker tag $App ghcr.xxxx.com/$GITHUB_REPOSITORY:cicd
            docker push ghcr.xxxx.com/$GITHUB_REPOSITORY:cicd
            docker tag $App ghcr.xxxx.com/$GITHUB_REPOSITORY:${{ github.sha }}
            docker push ghcr.xxxx.com/$GITHUB_REPOSITORY:${{ github.sha }}
        
        - name: 🍭 Attach container image to release
          uses: docker/metadata-action@v3
          with:
            images: ghcr.xxxx.com/xx/$ECR_REPOSITORY:cicd
            release: Version ${{ steps.autotagger.outputs.tag }}
            registry: ghcr.xxxx.com
            token: ${{ secrets.GH_PAT }}

**Comment by shaypi** [comment]
> Can you share your workflow yaml file?
> 
> Sorry the delay responding to this.
> 
> Still looks like a credentials problem.
name: xxxx JAR Assemble And Build
on:
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  REGISTRY: containers.github.xxxx.com/
jobs:
  
  cicd:
    if: ${{ !startsWith(github.event.pull_request.base.ref, 'staging') && !startsWith(github.event.pull_request.base.ref, 'master') && !startsWith(github.event.pull_request.base.ref, 'development') }}
    # if: ${{ github.event.pull_request.base.ref == 'cicd' }}
    name: xxx
    environment: cicd
    runs-on: xxx-runner-deployment
    timeout-minutes: 60
    steps:
    - name: ⬇️ Checkout xxx
      uses: actions/checkout@v3
      with:
        repository: xxx/xxx
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GH_PAT }}
    
    - name: ⚙️ running compose
      working-directory: .ci
      run: |
        echo "Running MONGO container in detached mode"
        docker-compose --file testsmongo-compose.yml up --detach --remove-orphans
        echo "Runnning SBT image"
        docker-compose --file buildsbtdocker-compose.yml up --abort-on-container-exit
        exit_code=$?
        if [ $exit_code -ne 0 ]; then
          exit $exit_code
        fi
        echo "Building xxxx-storage docker image"

    - name: 👀 Tag
      # if: github.event.pull_request.merged == true
      id: autotagger
      uses: anothrNick/github-tag-action@1.55.0
      env:
        GITHUB_TOKEN: "${{ secrets.GH_PAT }}"
        WITH_V: true

    - name: echo Tag
      run: echo ${{ steps.autotagger.outputs.tag }}

    - name: 🐱‍🚀 Release
      id: create_release
      if: steps.autotagger.outputs.tag != ''
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        tag_name: ${{ steps.autotagger.outputs.tag }}
        release_name: Version ${{ steps.autotagger.outputs.tag }}
        draft: false
        prerelease: false
    
    - name: 🔑 Login to AWS
      run: aws ecr get-login-password | docker login --username AWS --password-stdin xxxx.dkr.ecr.eu-west-1.amazonaws.com

    - name: 🔑 Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.xxxx.com
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PAT }}
    
    - name: 🐳 Build, tag, and push image to Amazon ECR
      env:
        App: airflow_xxxx_storage
        ECR_REGISTRY: xxxx.dkr.ecr.eu-west-1.amazonaws.com
        ECR_REPOSITORY: microservices
        IMAGE_TAG:  ${{ github.sha }}
      run: |
        docker build -t airflow_xxxx_storage -f .ci/Dockerfile .
        docker tag $App $ECR_REGISTRY/$ECR_REPOSITORY:$App-$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$App-$IMAGE_TAG
        docker tag $App $ECR_REGISTRY/$ECR_REPOSITORY:$App
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$App
        docker tag $App ghcr.xxxx.com/$GITHUB_REPOSITORY:cicd
        docker push ghcr.xxxx.com/$GITHUB_REPOSITORY:cicd
        docker tag $App ghcr.xxxx.com/$GITHUB_REPOSITORY:${{ github.sha }}
        docker push ghcr.xxxx.com/$GITHUB_REPOSITORY:${{ github.sha }}
    
    - name: 🍭 Attach container image to release
      uses: docker/metadata-action@v3
      with:
        images: ghcr.xxxx.com/xx/$ECR_REPOSITORY:cicd
        release: Version ${{ steps.autotagger.outputs.tag }}
        registry: ghcr.xxxx.com
        token: ${{ secrets.GH_PAT }}

**Comment by sbe-arg** [comment]
I don't see any dockerhub authentication

There should be something like this before the tag job

https://github.com/docker/login-action#docker-hub

Closing ticket for now
