### ISSUE TITLE
I can't get #patch or #major to work... ? 

### ISSUE THREAD

**Issue by fredbradley** [anothrNick/github-tag-action#250]
I've tried writing a commit message with #patch in the message and it's still giving me a minor bump.... I must be doing something wrong, but not sure what? Any hints? 

![Screenshot 2023-03-10 at 14 07 37](https://user-images.githubusercontent.com/1639226/224337047-00ad77c5-724d-4208-99b4-c34a65fabc4a.png)

**Comment by sbe-arg** [comment]
Please share your workflow configuration.

**Comment by sbe-arg** [comment]
Also tag history of your repo is possible.

**Comment by miguelaferreira** [comment]
I'm having the same issue, but I can't reproduce it in another repo. I've made a [test repo](https://github.com/miguelaferreira/test-github-tag-action), where I pushed different bump commits and the action worked as expected. I then also tried to do the same thing via a PR and it still worked as expected.

Tests:
- Workflows for single bump commit pushed to main
  - [patch](https://github.com/miguelaferreira/test-github-tag-action/actions/runs/4424419480/jobs/7758224391#step:4:31) 
  - [minor](https://github.com/miguelaferreira/test-github-tag-action/actions/runs/4424422568/jobs/7758229813#step:4:31)
  - [major](https://github.com/miguelaferreira/test-github-tag-action/actions/runs/4424425203/jobs/7758235720#step:4:29)
- [Workflow for change log containing a bump commit, pushed to main](https://github.com/miguelaferreira/test-github-tag-action/actions/runs/4424432388/jobs/7758252887#step:4:31) 
- [Workflow for bump in PR change log](https://github.com/miguelaferreira/test-github-tag-action/actions/runs/4424443852/jobs/7758278653#step:4:34)

The one difference I see between the workflows where the bumps aren't working and the test repository workflows, is that I don't see the history output from the action in the workflows that don't bump properly.

Example of missing output in workflows that don't bump properly.
```
History:
---
bump #minor
---
Bumping tag 0.1.1 - New tag 0.2.0
```

**Comment by miguelaferreira** [comment]
Bumping the action to version 1.61.0 (the same I use in the test repos) fixed the bumping via commit tags.

**Comment by sbe-arg** [comment]
Yes there was a history handling problem between versions 1.55-1.61 that took a while to get in a sort of okay state for most use cases.

I recommend either stay on versions before 1.5x and skip 1.5x versions altogether to 1.6x if there are any problems
