### ISSUE TITLE
Tags get greated but not releases

### ISSUE THREAD

**Issue by FredLavoie** [anothrNick/github-tag-action#255]
I've tried using merge commits and squash commits with one of the keywords in the commit message, and I've also tried adding the `#major` or `#patch` keywords in one of the commits in a PR itself, and when I merge, a tag gets created, but a release is not created. I'm merging a feature branch into `main`.

I've tried about 8 times, and it never seems to work. Here is my config:

![image](https://user-images.githubusercontent.com/17567331/234007296-37914992-698f-4ab2-b9c4-d449edd70df9.png)

Is there anything obvious that I'm doing wrong? Is it related to the error I'm seeing `fatal: ambiguous argument 'main..HEAD'` ?

**Comment by FredLavoie** [comment]
Ah ok, thank you. I misinterpreted this line under the Workflow heading of the README

> If triggered on your repo's default branch (master or main if unchanged), the bump version will be a release tag.

**Comment by sbe-arg** [comment]
Thats good feedback we should improve the readme. Thanks
