### ISSUE TITLE
Can this work with Branch Protection?

### ISSUE THREAD

**Issue by kroese** [anothrNick/github-tag-action#256]
I have my master branch protected so that it only accepts pull request and not normal pushes.

The other tag actions I tried could not work with this, so I am wondering if this one can? And if not, is there some workaround possible? For example by adding the tag push to the current pull request for example?

**Comment by sbe-arg** [comment]
Can you share your workflow config and runner logs?

**Comment by sbe-arg** [comment]
Have a look we don't do a git push https://github.com/anothrNick/github-tag-action/blob/1.62.0/entrypoint.sh#L236-L258 

Share de logs please.

I personally use this in many many repos with extreme branch protections and the tags work like charm.

**Comment by sbe-arg** [comment]
More relevant information https://github.com/anothrNick/github-tag-action/pull/210
