### ISSUE TITLE
Maybe something wrong in commit 72f3a54

### ISSUE THREAD

**Issue by sion56** [anothrNick/github-tag-action#260]
Currently, using git-tag-action will fail and give some logs like this, even though it was working until yesterday.

```
History:
---
Update flow.
---
/entrypoint.sh: line 54: : No such file or directory
Bumping tag v1.1.0 - New tag 1.2.0
```

And I found there is a change 4 hours ago, maybe something wrong in that commit?

**Comment by sbe-arg** [comment]
can you enable debug and paste the workflow config + runner logs.

line 54 is about setting the github outputs which they work in the tests https://github.com/anothrNick/github-tag-action/actions/runs/4900880477

**Comment by sbe-arg** [comment]
did some testing here https://github.com/sbe-arg/dummy-releases/actions

did find a problem while direct pushing to main requiring permissions but is not directly related to entrypoint also found the tag validating when no tags exist and opened a pr here https://github.com/anothrNick/github-tag-action/pull/261

**Comment by mellvelin** [comment]
I also faced error in my Github Actions after actions updated to mentioned commit.I'm not sure but maybe there is something with new node18 image.In my case i have following error massage:
`"/usr/bin/ssh" -i "$RUNNER_TEMP/12534357-e475-4aa3-a3ba-a1cf4d3091d3" -o StrictHostKeyChecking=yes -o CheckHostIP=no -o "UserKnownHostsFile=$RUNNER_TEMP/12534357-e475-4aa3-a3ba-a1cf4d3091d3_known_hosts": line 0: /usr/bin/ssh: not found`
