### ISSUE TITLE
Action fall in error after latest update

### ISSUE THREAD

**Issue by mellvelin** [anothrNick/github-tag-action#262]
I am facing error in my Github Actions after action updated to latest commit.I'm not sure but maybe there is something with new node18 image.In my case i have following error message:
`"/usr/bin/ssh" -i "$RUNNER_TEMP/12534357-e475-4aa3-a3ba-a1cf4d3091d3" -o StrictHostKeyChecking=yes -o CheckHostIP=no -o "UserKnownHostsFile=$RUNNER_TEMP/12534357-e475-4aa3-a3ba-a1cf4d3091d3_known_hosts": line 0: /usr/bin/ssh: not found`

**Comment by mellvelin** [comment]
And caught another error like this with new version which look like that: 
`fatal: ambiguous argument '0.0.0': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'`

Moved to 1.62.0 and all works like expected.

**Comment by sbe-arg** [comment]
Is this in a fresh repo without tags?

**Comment by sbe-arg** [comment]
I think is related to this https://github.com/anothrNick/github-tag-action/issues/260#issuecomment-1543328425
