### ISSUE TITLE
Action is incompatible with actions/checkout@master

### ISSUE THREAD

**Issue by pavyarov** [anothrNick/github-tag-action#27]
Action is incompatible with latest version of actions/checkout, because they change default fetch behavior, now fetches only the SHA being checked-out. [See more](https://github.com/actions/checkout/releases/tag/v2-beta).

Now we should manually fetch tags by `git fetch --tags`
[More info](https://github.com/actions/checkout/issues/85)

**Comment by anothrNick** [comment]
Wow good catch! This didn't cause a failure, unfortunately, so I didn't get notified.

**Comment by anothrNick** [comment]
Confirmed your contribution fixed this issue:

```
1.10.0
2019-12-04T20:11:18Z: **pushing tag 1.10.0 to repo anothrNick/github-tag-action
{
  "ref": "refs/tags/1.10.0",
  "node_id": "MDM6UmVmMjA1MDI0Mjk4OjEuMTAuMA==",
  "url": "https://api.github.com/repos/anothrNick/github-tag-action/git/refs/tags/1.10.0",
  "object": {
    "sha": "aca3c132f8bc18dd01554afb25d9c0d7b519e4ad",
    "type": "commit",
    "url": "https://api.github.com/repos/anothrNick/github-tag-action/git/commits/aca3c132f8bc18dd01554afb25d9c0d7b519e4ad"
  }
}
```

Thanks again!
