### ISSUE TITLE
"Resource not accessible by integration"

### ISSUE THREAD

**Issue by artdolya** [anothrNick/github-tag-action#275]
Hi!
I'm getting error from subject
I defined permissions for writing content
https://github.com/artdolya/Nlog.RabbitMQ/blob/master/.github/workflows/bump.yml#L30
But I'm getting error when someone else creates pull request, and it is merged to master
https://github.com/artdolya/Nlog.RabbitMQ/actions/runs/5566463491/jobs/10167591446#step:4:43

**Comment by sbe-arg** [comment]
Try setting GIT_API_TAGGING to false
