### ISSUE TITLE
Unable to read the blogpost "Creating A Github Action to Tag Commits"

### ISSUE THREAD

**Issue by marvindanig** [anothrNick/github-tag-action#277]
The README has a link to the following documentation/blog:

[Creating A Github Action to Tag Commits](https://itnext.io/creating-a-github-action-to-tag-commits-2722f1560dec).

The link opens but only with partial content and a prompt to signup (see screenshot):

![locked](https://github.com/anothrNick/github-tag-action/assets/5659924/618ca1a3-07ae-4825-939c-1f737312e127)

Is this site behind Medium or something? It says, "Read the full story with a free account." whereas this blog post isn't a newsy story or an opinion post. Can we move the post here within the repository next to the README or somewhere that is more open?

**Comment by sbe-arg** [comment]
a few things
1: I can see the article without any issues once I log to medium.
2: That post was created by @anothrNick the owner of the repo wich has not contributed to the library in a few years. 
3: If you open a pr to remove the url Ill approve it. Nothing else will be done from me on this topic.

cheers

**Comment by anothrNick** [comment]
@marvindanig ITNext is just a publication for Medium. So, yes, you need a medium account to read.
