### ISSUE TITLE
Shoutout Nick!

### ISSUE THREAD

**Issue by theorlandog** [anothrNick/github-tag-action#283]
Not an issue, just leaving a shutout to @anothrNick. I was going through a clients codebase and saw references back to this code. Small world; cool to see your work popping up.  Bobcats for life! ahaha

**Comment by anothrNick** [comment]
Haha hey man, thanks for leaving the comment. I hope it's working well for your client 😄.

Good to hear from you, I hope all is well.

**Comment by theorlandog** [comment]
Yes, it works great for them. My contribution is to nag the teams to pin to a commit hash for supply chain security reasons.

I'll definitely keep it in my back pocket of tricks. Hope all is well with you as well!
