### ISSUE TITLE
Entire History Being Evaluated on Merge

### ISSUE THREAD

**Issue by harrisoncramer** [anothrNick/github-tag-action#292]
Hello,

I'm trying to configure this action to only run on merges into the main branch. However, no matter which example I use from the provided examples, it seems to always evaluate the entire commit history and finds "stale" version tags. For instance, you can see on this CI action, it's evaluating a minor version bump:

https://github.com/harrisoncramer/gitlab.nvim/actions/runs/6916498193/job/18816643747

Despite having no description in the MR:

https://github.com/harrisoncramer/gitlab.nvim/pull/112

The #MINOR tag was included in a previous commit, however, which is getting picked up and used by the CI to make the bump. I've tried a variety of YAML configurations without any luck. Any advice here?

**Comment by sbe-arg** [comment]
Depending on your merge strategy you need to set BRANCH_HISTORY env var to last instead of compare

https://github.com/harrisoncramer/gitlab.nvim/blob/main/.github/workflows/tags.yaml

**Comment by harrisoncramer** [comment]
Ah, that did it. Thank you!
