### ISSUE TITLE
Tag precedence  with v and without

### ISSUE THREAD

**Issue by mellvelin** [anothrNick/github-tag-action#298]
I faced exact same problem mentioned here: 
https://github.com/anothrNick/github-tag-action/issues/76

I had verwioning with v and i want to continue without.
Action takes latest version with v all the time even though there is already new verwion without which was created by action beforhands.
So the issue persists in 1.67.0

**Comment by sbe-arg** [comment]
The easiest fix is to re tag the latest tag vX.Y.X as X.Y.Z manually changing the action WITH_V false and future tags will be without v.

Although this change from V to no V used to work without manual actions.

**Comment by mellvelin** [comment]
Unfortunatly it does not work like that.
Here is example what's going on:

- i have tag v.1.2.3
i run action with WITH_V: false
it genetrates 1.2.4 
so far so goon no problems

- next run it should be like : 
since it created 1.2.4 next should be 1.2.5
but instead of do this action takes once again v1.2.3
and bumps it again to 1.2.4 which lead to an obvious error that tag already exists

I tried to rename v.1.2.3 to 1.2.3 (  without v) manually

After that manipulation the result it that it just takes latest version with v anyway it this case v.1.2.2 but not one i created which 1.2.3

**Comment by sbe-arg** [comment]
Can you share the entire github action yaml and the verbose logs of the action run?

**Comment by sbe-arg** [comment]
https://github.com/anothrNick/github-tag-action/blob/master/entrypoint.sh#L96

That part is the one that should grab the latest X.Y.Z regardless the V or not V and then depending your settings add or not the V at the outputs section.

**Comment by sbe-arg** [comment]
It was made like that to allow switching back and fw from to V no V format.

It was working in the past.
