### ISSUE TITLE
Taking too long to bump and create new tag

### ISSUE THREAD

**Issue by jpulgar4** [anothrNick/github-tag-action#304]
When running this action in a larger repository with more than 16,000 tags present, it takes too long to generate the new tag (upwards of 2 minutes). I tried several configurations, even limiting fetch-depth on the checkout action to 100, however it still takes more than 2 minutes to complete. Here is our current configuration for it:
```
Run anothrNick/github-tag-action@1.67.0
*** CONFIGURATION ***
	DEFAULT_BUMP: patch
	DEFAULT_BRANCH: 
	WITH_V: true
	RELEASE_BRANCHES: main
	CUSTOM_TAG: 
	SOURCE: .
	DRY_RUN: false
	GIT_API_TAGGING: true
	INITIAL_VERSION: 0.0.0
	TAG_CONTEXT: repo
	PRERELEASE: true
	PRERELEASE_SUFFIX: preview
	VERBOSE: false
	MAJOR_STRING_TOKEN: #major
	MINOR_STRING_TOKEN: #minor
	PATCH_STRING_TOKEN: #patch
	NONE_STRING_TOKEN: #none
	BRANCH_HISTORY: last
```
What happens instead:

Takes too long to finish, upwards of 2 minutes per run.

What do I expect to happen:

Take shorter amount of time with the appropriate configuration.

Is there a way to specify how many tags or commits it will fetch when the `git fetch --tags` step happens? (from enabling `VERBOSE: true`)

**Comment by sbe-arg** [comment]
16k tags. Nice

**Comment by jpulgar4** [comment]
When not using `fetch-depth: 0` on the checkout action, `git fetch --tags` command will take too long to fetch all the remaining tags for larger repositories with a lot of tags (over 16,000).
