### ISSUE TITLE
Make optional "Skip if there are no new commits in pre-release re runs"

### ISSUE THREAD

**Issue by druskus20** [anothrNick/github-tag-action#309]
## Motivation:
The behaviour I want is to force a tag bump even if there are no changes - in order to keep versions matching with other apps / deployments. 

As I understand this is the default behavior. **However** I am using a separate release action. This means that I am forced to run github-tag-action in **pre-release** mode. 

## Solution

As I understand, putting the checks implemented in #234 behind a parameter should be enough - such as "SKIP_NO_COMMITS_PRERELEASE"

**Comment by sbe-arg** [comment]
Thanks for opening https://github.com/anothrNick/github-tag-action/pull/310 although if we merge it we cannot release it atm.
