### ISSUE TITLE
Marketplace has no releases since `1.8.0`

### ISSUE THREAD

**Issue by bwbaugh** [anothrNick/github-tag-action#31]
The `README` on the marketplace appears to be using `master` as it references things like `CUSTOM_TAG` but the `Use latest version` button provides `1.8.0` and none of the versions after that.

Manually referencing later tags works even though they don’t show up under [releases](https://github.com/anothrNick/github-tag-action/releases).

**Comment by anothrNick** [comment]
I've just published 1.11.0. Thank you.
