### ISSUE TITLE
Release branch matching is too unrestricted

### ISSUE THREAD

**Issue by J4NS-R** [anothrNick/github-tag-action#318]
https://github.com/anothrNick/github-tag-action/blob/ce4b5ffa38e072fa7a901e417253c438fcc2ccce/entrypoint.sh#L37

In the case of `main`, this check will match any branch that contains the word `main`, such as `maintenance`. This is obviously not the intention.

Perhaps the default should be changed to `^main$,^master$` instead.

Let me know and I'll make a PR

**Comment by sbe-arg** [comment]
On point

**Comment by J4NS-R** [comment]
Oh I see this has been fixed on main. We were using `v1.36.0`.
