### ISSUE TITLE
get largest semver tag, not most recent tag

### ISSUE THREAD

**Issue by chrishiestand** [anothrNick/github-tag-action#35]
In the current behavior, this action will find the most recent tag. However it is not guaranteed this will always be a semver tag. This may break things when manual tagging (or tagging via other sources) is done.

Instead, this action should find the largest semver version tag and use that instead.

**Comment by samlown** [comment]
This PR should fix that: https://github.com/anothrNick/github-tag-action/pull/37

**Comment by anothrNick** [comment]
Good catch! @samlown fixed this issue. 

Released with [1.13.0](https://github.com/anothrNick/github-tag-action/tree/1.13.0)
