### ISSUE TITLE
#minor doesnt seem to work

### ISSUE THREAD

**Issue by naknut** [anothrNick/github-tag-action#38]
Hi! I have a GitHub workflow set up in one of my repos that uses `github-tag-action` and it has been working great so far! Yesterday though I wanted to make a minor release of my library so I made a PR and added `#minor` in the commit message. The previous tag was 0.0.5 and the one created after the workflow ran was 0.0.6 even though I added `#minor`. You can see my full workflow here: https://github.com/naknut/Combinefall/blob/master/.github/workflows/Create%20Release.yml and my commit here: https://github.com/naknut/Combinefall/commit/7389267f70bb6938d091dca205a07e1e44709ef6

As you can see `#minor` is in the message but for some reason tag 0.0.6 was created. Did I do something wrong or is this a bug?

*Note: If you check the tags now the latest one says 0.1.0 but that is because I manually edited the tag to have the correct semver.*

**Comment by anothrNick** [comment]
Looks like there may be a bug with the configured default value overriding anything in the commit message. I should be able to test and confirm later today.

Thank you for submitting the issue!

**Comment by naknut** [comment]
> Looks like there may be a bug with the configured default value overriding anything in the commit message. I should be able to test and confirm later today.
> 
> Thank you for submitting the issue!

No problem at all! Let me know if there is anything I can do to help.

**Comment by anothrNick** [comment]
Looks like the full log of commits from the last tag to HEAD isn't being retrieved correctly, as seen from the output here:

**Comment by anothrNick** [comment]
@naknut set the `fetch-depth` on `actions/checkout@master` so all commit history is retrieved. I've updated the readme with:

```
    - uses: actions/checkout@master
      with:
        fetch-depth: '0'
```

**Comment by naknut** [comment]
Oh yeah! That could be it. But as you can see the commit that triggered the action had `#minor` in the message. So if I only fetched the latest commit it should have had that right?

**Comment by anothrNick** [comment]
The merge to master will be its own commit (the or merge) which is the last commit

**Comment by naknut** [comment]
Yes but I did set the #minor in the message for the merge.

**Comment by naknut** [comment]
https://github.com/naknut/Combinefall/commit/7389267f70bb6938d091dca205a07e1e44709ef6 Is the merge commit right? And the one that triggered the build. And the full commit message is:

> Merge pull request #12 from naknut/cardCollection
>Card Collection publishers #minor
