### ISSUE TITLE
Bump tag for checked out branch

### ISSUE THREAD

**Issue by mwaggett** [anothrNick/github-tag-action#51]
This action can run on any number of branches, but the action always looks for the latest tag and bumps that: https://github.com/anothrNick/github-tag-action/blob/master/entrypoint.sh#L28

Instead, look at the ref of the branch that triggered the action (e.g. via `git describe`) and bump that.

**Comment by Smudge3806** [comment]
+1

**Comment by Smudge3806** [comment]
I added a `TAG_CONTEXT` env var that swaps out the functionality of the `git for-each-ref` and subs in the `git describe`. The filtering behavior of the original is carried to the `describe` functionality. 

```yaml
env:
  - TAG_CONTEXT=branch
```
