### ISSUE TITLE
DRY_RUN property set to true; tag being generated

### ISSUE THREAD

**Issue by tamoore** [anothrNick/github-tag-action#52]
I tried using your action (thank you for sharing it). Unfortunately the `DRY_RUN` env var does not appear to do what it says on the tin.

I set it to true, but in the run it still created a tag on the `master` branch. 

Steps to reproduce:

1. Create a workflow with this action and run the workflow with some new commit
2. Set DRY_RUN to true
3. See tag printed to stdout
4. See tag in Releases tab within the github UI.

Version `1.13.0`

**Comment by anothrNick** [comment]
Please try with the latest version `1.18.0`. I don't believe `DRY_RUN` existed in `1.13.0`.

**Comment by tamoore** [comment]
I was the latest, I assumed from your releases page that was 1.13.0.

Check the code in entrypoint.sh. You do nothing with assignment DRY_RUN. It's just given a default of `false`. But other then that, no conditional, nothing.

**Comment by anothrNick** [comment]
https://github.com/anothrNick/github-tag-action/blob/1.18.0/entrypoint.sh#L86
