### ISSUE TITLE
Allow only manual bumping (DEFAULT_BUMP=none)?

### ISSUE THREAD

**Issue by Eun** [anothrNick/github-tag-action#56]
It would be great to have the possibility to disable automatic bumping and only have manual bumping.

Maybe solvable by allowing a `DEFAULT_BUMP=none` case?

**Comment by dmerrick** [comment]
I'd love to see this!

**Comment by dmerrick** [comment]
I took a pass at adding this: https://github.com/anothrNick/github-tag-action/pull/59

**Comment by anothrNick** [comment]
Available in 1.22.0
