### ISSUE TITLE
Bump tag with rc suffix

### ISSUE THREAD

**Issue by vivekwolf123** [anothrNick/github-tag-action#57]
Is it possible to bump with tag version that contains `rc` suffix for eg: `1.0.0-rc`. If yes, how is it possible?

**Comment by anothrNick** [comment]
Currently you can override the dynamic tag with the `CUSTOM_TAG` environment variable. There is no dynamic way to tag with a suffix.

**Comment by vivekwolf123** [comment]
Cool, thanks for the info
