### ISSUE TITLE
Semver tags for this repo

### ISSUE THREAD

**Issue by sjauld** [anothrNick/github-tag-action#61]
Thanks for this plugin!

It would be great if you could tag this repo with `v1` so that I can track the latest safe version rather than having to bump every time you do a non-breaking release!

I guess this could also be a feature request for this plugin, e.g. when I would normally tag my repo with `v1.3.4`, also tag it with `v1.3` and `v1`.

Happy to look at putting together a PR if you think this would be a helpful addition.

**Comment by dmerrick** [comment]
+1

I'd love to see this so you could pin a version at `v1.0` and get the latest `v1.0.x`

**Comment by anothrNick** [comment]
This would be great to have, although I'm not quite sure what the implementation would look like. Would this need to update an existing tag to point to the latest (most appropriate) commit? Or do we just need to push the "base" tags and Github will automagically pull the correct semver tag?

If you could submit a PR for this it would be greatly appreciated!

**Comment by wyndigo** [comment]
This would be amazing and it exactly what I need. I think you can just push a new version of the tag.

**Comment by sammcj** [comment]
This is now in place.
