### ISSUE TITLE
Issue with squashed commits 

### ISSUE THREAD

**Issue by CalvinRodo** [anothrNick/github-tag-action#63]
Hi I'm trying to use this action as part of our build process and it's only ever bumping us on the minor version. 

You can see an example of a commit that didn't trigger a minor increase 

https://github.com/cds-snc/c19-benefits-node/commit/982a0ac85530717c4607215c95dc6fac4353278b

Here is the action that runs on push to master 
https://github.com/cds-snc/c19-benefits-node/blob/master/.github/workflows/build-deploy-dev.yml

**Comment by jakebanks** [comment]
May be related, I am observing that it only finds the keywords in merge commit titles or bodies (squashed in this case as well). This is with the clone depth property set.

**Comment by sammcj** [comment]
Hello - is this still an issue with v1.45.0 and required?

**Comment by sbe-arg** [comment]
Closing please reopen if necesary
