### ISSUE TITLE
Issue with new tag not getting pushing to repo and workflow silently failing

### ISSUE THREAD

**Issue by trevor92** [anothrNick/github-tag-action#71]
The issue that I am facing is that when i run this action on a test branch with the release branches variable set a new tag is generated fine. However on master when my workflow is triggered on a schedule, the action seems to not push the tag and silently the workflow fails with no error message. Am I missing something?

**Comment by danielmklein** [comment]
@trevor92 shot in the dark here, but is your release branch actually named **master?** We saw this action start silently failing when we renamed our production-ready branch from **master** to **main**, and I'm wondering if you might be hitting the same case!

**Comment by NickLarsenNZ** [comment]
This action should have the same behavior for `main` as it has with `master`. This caught me today too.

**Comment by sammcj** [comment]
Hello I believe this has been resolved, please let me know if it hasn't and I'll reopen.
