### ISSUE TITLE
Tags with v prefix take precedence over those without 

### ISSUE THREAD

**Issue by eakman-nomad** [anothrNick/github-tag-action#76]
## Problem Description
Noticed something a little odd. The problem is a little complex, but will try to break it down as simply as possible.

I initially started using `github-tag-action` without the `WITH_V` option. When my project was at version number `0.1.0` I decided to set the `WITH_V` option to true. I then pushed a patch and the resulting tag was as expected `v0.1.1`. I then removed the `WITH_V` option and pushed another patch and the resulting tag was `0.1.2`. I then pushed several more patches, but the version number did not increment and each time I saw the following logs in the workflow:

```
patch
0.1.2
2020-08-08T23:11:08Z: **pushing tag 0.1.2 to repo ****/****
{
  "message": "Reference already exists",
  "documentation_url": "https://docs.github.com/rest/reference/git#create-a-reference"
}
```

It seems `github-tag-action` kept trying to push `0.1.2` even though that version number already existed. Apparently it was picking up `v0.1.1` as the latest tag each time. After removing this tag, the problem disappeared.

**Comment by fermoya** [comment]
[This pull-request](https://github.com/anothrNick/github-tag-action/pull/83/files) solves the issue. It's a matter of replacing `--sort=-v:refname` with `--sort=-committerdate`

**Comment by eakman-nomad** [comment]
> [This pull-request](https://github.com/anothrNick/github-tag-action/pull/83/files) solves the issue. It's a matter of replacing `--sort=-v:refname` with `--sort=-committerdate`. If you want to try it, use my fork till this PR gets merged

Much appreciated 🙏 🙏

**Comment by fermoya** [comment]
Note here version 1.33.0 breaks this again as the tags sort by parameter changed from `committerdate` to `v:refname`. For more info, see the pull-request that introduced the issue:
https://github.com/anothrNick/github-tag-action/pull/86

**Comment by sammcj** [comment]
Hello @fermoya @jesigloot - is this still an issue with v1.45.0 and required?

**Comment by sbe-arg** [comment]
Closing beleive its been fixed please reaopen if necesary
