### ISSUE TITLE
Setting DEFAULT_BUMP to none fails step

### ISSUE THREAD

**Issue by sarahethompson** [anothrNick/github-tag-action#77]
If I set DEFAULT_BUMP to none in my actions.yml and don't include #major, #minor or #patch in the commit message, I get a failed step with the below error message. It looks like it's trying to push a tag 'refs/tags/Default bump was set to none. Skipping...' when it should be skipping this entirely?

```
Default bump was set to none. Skipping...
fatal: too many params
2020-08-18T11:37:53Z: **pushing tag Default bump was set to none. Skipping... to repo sarahethompson/actions-test
  "message": "refs/tags/Default bump was set to none. Skipping... is not a valid ref name.",
  "documentation_url": "https://docs.github.com/rest/reference/git#create-a-reference"
}
```

```
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.SARAH_ACTIONS_PAT }}
        DEFAULT_BUMP: none
        TAG_CONTEXT: branch
        RELEASE_BRANCHES: release/.*,master
```

**Comment by Norgul** [comment]
This still doesn't work. Any updates?

**Comment by gacarrillor** [comment]
> This still doesn't work. Any updates?

It does!. 

Chances are that you need to use a more recent version of the GitHub action. 
For instance `anothrNick/github-tag-action@1.34.0`

**Comment by Norgul** [comment]
> Chances are that you need to use a more recent version of the GitHub action.
> For instance `anothrNick/github-tag-action@1.34.0`

This resolves it, thanks!

**Comment by kekhuay** [comment]
the latest version still not work for me.

**Comment by sammcj** [comment]
Hello - is this still an issue with v1.45.0 and required?

**Comment by sarahethompson** [comment]
> 

Yes this was fixed in https://github.com/anothrNick/github-tag-action/pull/79. Going to close this issue.
