### ISSUE TITLE
[error]Tag was not created properly.

### ISSUE THREAD

**Issue by leo108** [anothrNick/github-tag-action#84]
I'm using anothrNick/github-tag-action@1.26.0 and enabled debug mode, the debug message of this line is empty https://github.com/anothrNick/github-tag-action/blob/1.26.0/entrypoint.sh#L151

https://github.com/leo108/geolite2-db/runs/1079131682?check_suite_focus=true

This workflow works well when triggered manually, but always failed when triggered by github action schedule.

**Comment by ondrejmirtes** [comment]
I have the same problem: https://github.com/phpstan/php-8-stubs/runs/1223450554?check_suite_focus=true

**Comment by anothrNick** [comment]
I think this might be related: https://github.com/anothrNick/github-tag-action/issues/22

> If you want to trigger an action from an action you should use a personal github token instead of `secrets.GITHUB_TOKEN`

**Comment by leo108** [comment]
Using a personal token doesn't fix the issue:
Workflow: https://github.com/leo108/geolite2-db/runs/1272531346?check_suite_focus=true#step:11:47
Workflow File: https://github.com/leo108/geolite2-db/actions/runs/314416440/workflow#L73 I have replace the GITHUB_TOKEN to ROOT_ GITHUB_TOKEN, it's my personal token, which works well by manual trigger

**Comment by leo108** [comment]
@ondrejmirtes Did you find the solution to the issue?

**Comment by mnajjarian** [comment]
Replacing steps and move the action before deploying solved my problem. Another solution could be to put it in another job.

**Comment by sahandsn** [comment]
same issue

**Comment by sbe-arg** [comment]
@sahandsn read the docs
