### ISSUE TITLE
[Feature] Option to remove version from `release` folder

### ISSUE THREAD

**Issue by snwflake** [anothrNick/github-tag-action#85]
Currently, when moving all my files into the release folder, the version is appended to both the zip and the containing folder.
```
release-0.1.0.zip
└───release-0.1.0
    │   file1.foo
    │   file2.foo
```

Since I'm using this for a plugin, the containing folder has to retain it's name, without the version appended.
I don't want to wrap it into yet another folder, or force users to rename it after unzipping.

Any chance support for that can be added?

Cheers

**Comment by sammcj** [comment]
Hello @snwflake, This Action is for bump git tags, it doesn't touch the files/folders inside your repo, you may need another Action or a job which uses the output of this Action if you wish to do that.
