### ISSUE TITLE
Major bump not working as before since 1.29.0

### ISSUE THREAD

**Issue by jonbretman** [anothrNick/github-tag-action#87]
We use this action to create a new major version on every merge to master, but since 1.29.0 it keep trying to create the a most recently used tag, in this case 662.0.0.

We've reverted to 1.28.0 and it's working ok again so not sure what changed.

```
... omitted ...
2020-09-15T17:10:59.2448813Z  * [new tag]           662.0.0                 -> 662.0.0
2020-09-15T17:10:59.2449371Z  * [new tag]           67.0.0                  -> 67.0.0
2020-09-15T17:10:59.2449931Z  * [new tag]           68.0.0                  -> 68.0.0
2020-09-15T17:10:59.2450495Z  * [new tag]           69.0.0                  -> 69.0.0
2020-09-15T17:10:59.2451051Z  * [new tag]           7.0.0                   -> 7.0.0
2020-09-15T17:10:59.2451610Z  * [new tag]           70.0.0                  -> 70.0.0
2020-09-15T17:10:59.2452196Z  * [new tag]           70.100.1                -> 70.100.1
2020-09-15T17:10:59.2452763Z  * [new tag]           70.100.2                -> 70.100.2
2020-09-15T17:10:59.2453349Z  * [new tag]           70.101.1                -> 70.101.1
2020-09-15T17:10:59.2453917Z  * [new tag]           70.101.2                -> 70.101.2
2020-09-15T17:10:59.2454485Z  * [new tag]           70.99.1                 -> 70.99.1
... omitted ...
2020-09-15T17:10:59.2489855Z  * [new tag]           97.0.0                  -> 97.0.0
2020-09-15T17:10:59.2490442Z  * [new tag]           97.114.6                -> 97.114.6
2020-09-15T17:10:59.2491011Z  * [new tag]           97.114.7                -> 97.114.7
2020-09-15T17:10:59.2491578Z  * [new tag]           97.118.3                -> 97.118.3
2020-09-15T17:10:59.2492151Z  * [new tag]           97.118.4                -> 97.118.4
2020-09-15T17:10:59.2492720Z  * [new tag]           97.118.5                -> 97.118.5
2020-09-15T17:10:59.2493288Z  * [new tag]           97.118.6                -> 97.118.6
2020-09-15T17:10:59.2494435Z  * [new tag]           97.119.1                -> 97.119.1
2020-09-15T17:10:59.2495032Z  * [new tag]           98.0.0                  -> 98.0.0
2020-09-15T17:10:59.2495596Z  * [new tag]           99.0.0                  -> 99.0.0
2020-09-15T17:10:59.2496508Z  * [new tag]           99.119.2                -> 99.119.2
2020-09-15T17:10:59.2496956Z Trigger build
2020-09-15T17:10:59.3455660Z major
2020-09-15T17:10:59.3456024Z 662.0.0
2020-09-15T17:10:59.3497649Z fatal: tag '662.0.0' already exists
2020-09-15T17:10:59.3889592Z 2020-09-15T17:10:59Z: **pushing tag 662.0.0 to repo echo-health/prescriptions
2020-09-15T17:10:59.8752362Z   "message": "Reference already exists",
2020-09-15T17:10:59.8755460Z   "documentation_url": "https://docs.github.com/rest/reference/git#create-a-reference"
2020-09-15T17:10:59.8756893Z }
```

**Comment by anothrNick** [comment]
@fermoya Any idea on this?

**Comment by fermoya** [comment]
Hi @jonbretman , I’m having trouble understanding the issue. What’s your last tag and what’s the new tag created after the major bump?

**Comment by jonbretman** [comment]
@fermoya so the latest tag on the master branch is 662.0.0 (you can see it comes back in the list of existing tags in the output I posted), but since 1.29.0 this action seems to keep trying to make 662.0.0 _again_, which fails because it already exists.

I pinned this action to 1.28.0 and it worked again e.g. a 663.0.0 was created on the next master build.

**Comment by fermoya** [comment]
@jonbretman is your repo public? Could you share the link so that I fork it and take a look?

**Comment by jonbretman** [comment]
No it's a private repo. If I run that command on the master branch I get:

```
git for-each-ref --sort=-committerdate --format '%(refname)' | cut -d / -f 3- | grep -E "^v?[0-9]+.[0-9]+.[0-9]+$" | head -n1
663.0.0
```

663.0.0 is the latest tag on that branch

**Comment by fermoya** [comment]
And the configuration? What are the values for `TAG_CONTEXT`, etc?

**Comment by jonbretman** [comment]
This is our config:

```
- id: semver_tag
  uses: anothrNick/github-tag-action@1.28.0
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    DEFAULT_BUMP: major
```

**Comment by fermoya** [comment]
@anothrNick if the tag context is set to it’s default value, the last tag is fetched by the command @jonbretman executed locally (`git for-each-ref --sort=-committerdate --format '%(refname)' | cut -d / -f 3- | grep -E "^v?[0-9]+.[0-9]+.[0-9]+$" | head -n1`), which gave him `633.0.0` as a result. If you run `semver -i major 633.0.0` it returns `634.0.0` in my machine. 

I think we should add more logs to determine which tag is getting bumped and its result, not just the resulting tag.

In any case, this isn’t related to the beta versioning because this is generating release tags. I did make a change to sort tags by _committerdate_ and not by name as before (see [here](https://github.com/anothrNick/github-tag-action/commit/0263c1f2cd151d6016486219a6bc3dde36b26645#diff-b958f585a04af5ee2087610ea7180f34)). It might have been the problem.

Within the next days, I’ll set a test repo to try the different bumps available, I’ll let you know. I’ll also raise a PR to add more logs.

@jonbretman if you switched again to version 1.29.0 it should work as per the information shared here. It might be worth giving it a try to help us out here

**Comment by fermoya** [comment]
Hi @jonbretman , @anothrNick , I've set [this repo](https://github.com/fermoya/github-tag-action-test) to test bumps and they seem to work just fine.

**Comment by fermoya** [comment]
Added pull-request #89 to add more logs

**Comment by jonbretman** [comment]
Hey @fermoya thanks for looking into it. We've now seen this happen in a few of our repos so for now will keep pinned to 1.28.0 but if your PR is merged then happy to try latest again and can share logs.

**Comment by fermoya** [comment]
@jonbretman you can test it if you point to my repo `fermoya/github-tag-action@additional-logs`.

**Comment by anothrNick** [comment]
Merged #89. Logging should be available from `1.30.0`

**Comment by fermoya** [comment]
@jonbretman could you give it a try and let us know please?

**Comment by anothrNick** [comment]
FYI I've just `major` bumped another one of my projects with `anothrNick/github-tag-action@1.32.0` here - https://github.com/anothrNick/turtle-ui/runs/1243921170?check_suite_focus=true

**Comment by fermoya** [comment]
I've been using this too in [my repo](https://github.com/fermoya/SwiftUIPager) and it's been working great. If no any other complain, I'd close this issue

**Comment by bilalcaliskan** [comment]
i am also facing with that issue. i dont want to use major as default bump but when i add "#major" in the commit message it is no longer working. but i swear it was working on older versions.

**Comment by sammcj** [comment]
Hello - is this still an issue with v1.45.0?

**Comment by bilalcaliskan** [comment]
@sammcj it is even worse with v1.45.0 actually. I am getting that error on Github actions:

```
	git config --global --add safe.directory /github/workspace
fatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
No new commits since previous tag. Skipping...

```

**Comment by bilalcaliskan** [comment]
just another update, v1.45.0 is broken as i have mentioned on above comment but with v1.42.0 everything works like a charm!

**Comment by sammcj** [comment]
@bilalcaliskan can you please share your workflow here? (Remember to redact anything sensitive)

**Comment by bilalcaliskan** [comment]
@sammcj here is the related parts, rest of them are omitted:

```
  tag:
    runs-on: ubuntu-latest
    needs:
      - codeql
      - sonarcloud
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.45.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

  release:
    runs-on: ubuntu-latest
    needs:
      - tag
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set outputs
        id: vars
        run: |
          echo "::set-output name=latest_tag::$(git describe --tags $(git rev-list --tags --max-count=1))"
          echo "::set-output name=build_time::$(date -u +'%m-%d-%YT%H:%M:%SZ')"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --config build/package/.goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
```

**Comment by sammcj** [comment]
Thanks, I'm going to revert 1.45.0 for a number of reasons, but will try to have a look at this at some point but it might not be until next week.

**Comment by bilalcaliskan** [comment]
@sammcj i could find a chance to test with another version, 1.41.0, and i can happily verify that everything is working as expected, just for your information!

**Comment by sammcj** [comment]
Awesome! Thanks :)
