### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by nfcopier** [anothrNick/github-tag-action#88]
Are there any immediate plans to support running on Windows? If, any recommendations for alternatives?

**Comment by anothrNick** [comment]
Do you mean for the [Github hosted runner environments](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on)?

I'm not actively working on this project, so I don't have any plans to ensure it works on a windows runner (this action runs in a docker container, so I'm not sure what else would need to be done to make sure it works on any/all runner(s)).

https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners

I assume you've already tried on a windows runner and this action failed?

**Comment by nfcopier** [comment]
Correct. I will have to track down that error message again. But it was something to the effect of this action only being supported in Linux environments. If you're no longer actively working on this, I may just look into it myself when I find the time. Thanks.

**Comment by sammcj** [comment]
@nfcopier is this still a desired requirement or can I close this one off?

**Comment by nfcopier** [comment]
Go ahead and close.

**Comment by r-chaykovskiy** [comment]
> Please reopen this! As a Windows user, I am just running into this and I needed a quick way to generate new tags, and I am currently using time as a dirty workaround for it.

You could separate the tagging into a different job (with Linux) and use the output of this job

**Comment by HO-COOH** [comment]
@r-chaykovskiy Thanks, this is a brilliant workaround.
