### ISSUE TITLE
[Feature Request] Ability option automatically create releases with created tag

### ISSUE THREAD

**Issue by cynicaljoy** [anothrNick/github-tag-action#90]
I'd like to have the option to automatically [create the release](https://developer.github.com/v3/repos/releases/#create-a-release) version after the tag has been created. I'd anticipate that some people would want to be able to trigger this from a commit message hashtag. Personally, I'd prefer a boolean toggle:

```
env:
  CREATE_RELEASE: true
```

**Comment by anothrNick** [comment]
There is an official action to create a release - https://github.com/actions/create-release.

This action can be added to your workflow after the tag is created. The tag is available as an output that can then be passed to `actions/create-release`, along with the tag as a name and perhaps a version controlled file for release notes passed to `body_path`.
