### ISSUE TITLE
Initial Tagging prior to first release not working

### ISSUE THREAD

**Issue by ltshb** [anothrNick/github-tag-action#97]
When we don't have any initial release Tag in master (e.g. no v0.0.0 in master), the first merge in another branch creates a v0.1.0-beta.1 tag which is good. However on the second merge to another branch the bump version failed because it tries again to create a v0.1.0-beta.1 tag which already exists. This is due to the fact that the script doesn't found any release tag (e.g. v0.0.0) because it doesn't exist. To solve the issue I had to manually create a tag v0.0.0 on my master branch (I did it on the first commit of master).

**Comment by randykinne** [comment]
Having the same issue. Manually creating a v0.0.0 tag on `master` fixes the issue?

**Comment by joshcarp** [comment]
Thought I had the same issue but made a silly mistake and didn't give my pat repo scope and so it couldn't fetch the tags

**Comment by ivanpk** [comment]
I've opened a PR which tries to solve this issue:

Previous behavior:

```
Bumping tag 0.0.0. 
	New tag v0.0.1-rc.1
fatal: tag 'v0.0.1-rc.1' already exists
```

Now, it bumps pre-release tags as expected, even if it doesn't find a main release tag.

https://github.com/anothrNick/github-tag-action/pull/120

**Comment by arbob** [comment]
damn this issue hasn't been solved yet? Still getting the same error

**Comment by sammcj** [comment]
Hello - is this still an issue with v1.45.0 and required?
